
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EuropeMapPanel.java
 *
 * Created on 20-apr-2011, 22.08.01
 */

package virtualrisikoii.Map.europe;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import services.GameController;
import virtualrisikoii.XMapPanel;

/**
 *
 * @author root
 */
public class EuropeMapPanel extends XMapPanel {

  


    /** Creates new form EuropeMapPanel */
    public EuropeMapPanel() {
        gameController=GameController.getInstance();
        gameController.setMapListener(this);
        gameController.setTroopsSelector(this);
        gameController.setVictoryListener(this);
        gameController.setCardListener(this);
        initComponents();
        territoriLabels=new JLabel[42];
        territoriLabels[0]=islandaLabel;
        territoriLabels[1]=irlandaLabel;
        territoriLabels[2]=regnoUnitoLabel;
        territoriLabels[3]=norvegiaLabel;
        territoriLabels[4]=sveziaLabel;
        territoriLabels[5]=finlandiaLabel;
        territoriLabels[6]=russiaLabel;
        territoriLabels[7]=estoniaLabel;
        territoriLabels[8]=lituaniaLabel;
        territoriLabels[9]=russiaBiancaLabel;
        territoriLabels[10]=ucrainaLabel;
        territoriLabels[11]=kazakistanLabel;
        territoriLabels[12]=georgiaLabel;
        territoriLabels[13]=turchiaLabel;
        territoriLabels[14]=iranLabel;
        territoriLabels[15]=iraqLabel;
        territoriLabels[16]=siriaLabel;
        territoriLabels[17]=arabiaSauditaLabel;
        territoriLabels[18]=giordaniaLabel;
        territoriLabels[19]=egittoLabel;
        territoriLabels[20]=libiaLabel;
        territoriLabels[21]=tunisiaLabel;
        territoriLabels[22]=algeriaLabel;
        territoriLabels[23]=maroccoLabel;
        territoriLabels[24]=portogalloLabel;
        territoriLabels[25]=spagnaLabel;
        territoriLabels[26]=franciaLabel;
        territoriLabels[27]=italiaLabel;
        territoriLabels[28]=svizzeraLabel;
        territoriLabels[29]=paesiBassiLabel;
        territoriLabels[30]=germaniaLabel;
        territoriLabels[31]=danimarcaLabel;
        territoriLabels[32]=poloniaLabel;
        territoriLabels[33]=repubblicaCecaLabel;
        territoriLabels[34]=austriaLabel;
        territoriLabels[35]=slovacchiaLabel;
        territoriLabels[36]=ungheriaLabel;
        territoriLabels[37]=croaziaLabel;
        territoriLabels[38]=yugoslaviaLabel;
        territoriLabels[39]=greciaLabel;
        territoriLabels[40]=bulgariaLabel;
        territoriLabels[41]=romaniaLabel;

        LabelSelector selector=new LabelSelector();
        for(int i=0;i<territoriLabels.length;i++){
            this.territoriLabels[i].addMouseListener(selector);
        }

        initIconPlayers();
        gameController.initMap();


        
    }

   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        mapPanel1 = new virtualrisikoii.Map.europe.MapPanel();
        iranLabel = new javax.swing.JLabel();
        egittoLabel = new javax.swing.JLabel();
        iraqLabel = new javax.swing.JLabel();
        franciaLabel = new javax.swing.JLabel();
        italiaLabel = new javax.swing.JLabel();
        svizzeraLabel = new javax.swing.JLabel();
        germaniaLabel = new javax.swing.JLabel();
        islandaLabel = new javax.swing.JLabel();
        sveziaLabel = new javax.swing.JLabel();
        paesiBassiLabel = new javax.swing.JLabel();
        irlandaLabel = new javax.swing.JLabel();
        norvegiaLabel = new javax.swing.JLabel();
        russiaLabel = new javax.swing.JLabel();
        finlandiaLabel = new javax.swing.JLabel();
        regnoUnitoLabel = new javax.swing.JLabel();
        estoniaLabel = new javax.swing.JLabel();
        lituaniaLabel = new javax.swing.JLabel();
        russiaBiancaLabel = new javax.swing.JLabel();
        kazakistanLabel = new javax.swing.JLabel();
        ucrainaLabel = new javax.swing.JLabel();
        georgiaLabel = new javax.swing.JLabel();
        bulgariaLabel = new javax.swing.JLabel();
        romaniaLabel = new javax.swing.JLabel();
        greciaLabel = new javax.swing.JLabel();
        yugoslaviaLabel = new javax.swing.JLabel();
        croaziaLabel = new javax.swing.JLabel();
        slovacchiaLabel = new javax.swing.JLabel();
        ungheriaLabel = new javax.swing.JLabel();
        poloniaLabel = new javax.swing.JLabel();
        danimarcaLabel = new javax.swing.JLabel();
        repubblicaCecaLabel = new javax.swing.JLabel();
        austriaLabel = new javax.swing.JLabel();
        siriaLabel = new javax.swing.JLabel();
        giordaniaLabel = new javax.swing.JLabel();
        arabiaSauditaLabel = new javax.swing.JLabel();
        tunisiaLabel = new javax.swing.JLabel();
        maroccoLabel = new javax.swing.JLabel();
        libiaLabel = new javax.swing.JLabel();
        algeriaLabel = new javax.swing.JLabel();
        portogalloLabel = new javax.swing.JLabel();
        spagnaLabel = new javax.swing.JLabel();
        turchiaLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setName("jLabel2"); // NOI18N

        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.BorderLayout());

        mapPanel1.setName("mapPanel1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(EuropeMapPanel.class);
        iranLabel.setFont(resourceMap.getFont("iranLabel.font")); // NOI18N
        iranLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iranLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        iranLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        iranLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iranLabel.setName("iranLabel"); // NOI18N
        mapPanel1.add(iranLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 570, 80, 80));

        egittoLabel.setFont(resourceMap.getFont("iranLabel.font")); // NOI18N
        egittoLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        egittoLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        egittoLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        egittoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        egittoLabel.setName("egittoLabel"); // NOI18N
        mapPanel1.add(egittoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 680, 130, 20));

        iraqLabel.setFont(resourceMap.getFont("iranLabel.font")); // NOI18N
        iraqLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iraqLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        iraqLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        iraqLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        iraqLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iraqLabel.setName("iraqLabel"); // NOI18N
        mapPanel1.add(iraqLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 600, 70, 70));

        franciaLabel.setFont(resourceMap.getFont("iranLabel.font")); // NOI18N
        franciaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        franciaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        franciaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        franciaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        franciaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        franciaLabel.setName("franciaLabel"); // NOI18N
        mapPanel1.add(franciaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 120, 100));

        italiaLabel.setFont(resourceMap.getFont("iranLabel.font")); // NOI18N
        italiaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        italiaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        italiaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        italiaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        italiaLabel.setName("italiaLabel"); // NOI18N
        mapPanel1.add(italiaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 130, 80));

        svizzeraLabel.setFont(resourceMap.getFont("iranLabel.font")); // NOI18N
        svizzeraLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        svizzeraLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        svizzeraLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        svizzeraLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        svizzeraLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        svizzeraLabel.setName("svizzeraLabel"); // NOI18N
        mapPanel1.add(svizzeraLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 60, 40));

        germaniaLabel.setFont(resourceMap.getFont("iranLabel.font")); // NOI18N
        germaniaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        germaniaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        germaniaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        germaniaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        germaniaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        germaniaLabel.setName("germaniaLabel"); // NOI18N
        mapPanel1.add(germaniaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 70, 90));

        islandaLabel.setFont(resourceMap.getFont("iranLabel.font")); // NOI18N
        islandaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        islandaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        islandaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        islandaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        islandaLabel.setName("islandaLabel"); // NOI18N
        mapPanel1.add(islandaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 90, 100, 70));

        sveziaLabel.setFont(resourceMap.getFont("iranLabel.font")); // NOI18N
        sveziaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sveziaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        sveziaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        sveziaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        sveziaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sveziaLabel.setName("sveziaLabel"); // NOI18N
        mapPanel1.add(sveziaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 70, 160));

        paesiBassiLabel.setFont(resourceMap.getFont("iranLabel.font")); // NOI18N
        paesiBassiLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        paesiBassiLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        paesiBassiLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        paesiBassiLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paesiBassiLabel.setName("paesiBassiLabel"); // NOI18N
        mapPanel1.add(paesiBassiLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 50, 60));

        irlandaLabel.setFont(resourceMap.getFont("iranLabel.font")); // NOI18N
        irlandaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        irlandaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        irlandaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        irlandaLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        irlandaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        irlandaLabel.setName("irlandaLabel"); // NOI18N
        mapPanel1.add(irlandaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 50, 50));

        norvegiaLabel.setFont(resourceMap.getFont("iranLabel.font")); // NOI18N
        norvegiaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        norvegiaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        norvegiaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        norvegiaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        norvegiaLabel.setName("norvegiaLabel"); // NOI18N
        mapPanel1.add(norvegiaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 80, 80));

        russiaLabel.setFont(resourceMap.getFont("iranLabel.font")); // NOI18N
        russiaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        russiaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        russiaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        russiaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        russiaLabel.setName("russiaLabel"); // NOI18N
        mapPanel1.add(russiaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 340, 310));

        finlandiaLabel.setFont(resourceMap.getFont("iranLabel.font")); // NOI18N
        finlandiaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        finlandiaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        finlandiaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        finlandiaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        finlandiaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        finlandiaLabel.setName("finlandiaLabel"); // NOI18N
        mapPanel1.add(finlandiaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 80, 80));

        regnoUnitoLabel.setFont(resourceMap.getFont("iranLabel.font")); // NOI18N
        regnoUnitoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regnoUnitoLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        regnoUnitoLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        regnoUnitoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regnoUnitoLabel.setName("regnoUnitoLabel"); // NOI18N
        mapPanel1.add(regnoUnitoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 80, 150));

        estoniaLabel.setFont(resourceMap.getFont("iranLabel.font")); // NOI18N
        estoniaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        estoniaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        estoniaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        estoniaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        estoniaLabel.setName("estoniaLabel"); // NOI18N
        mapPanel1.add(estoniaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 80, 50));

        lituaniaLabel.setFont(resourceMap.getFont("iranLabel.font")); // NOI18N
        lituaniaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lituaniaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        lituaniaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        lituaniaLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lituaniaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lituaniaLabel.setName("lituaniaLabel"); // NOI18N
        mapPanel1.add(lituaniaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 90, 30));

        russiaBiancaLabel.setFont(resourceMap.getFont("iranLabel.font")); // NOI18N
        russiaBiancaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        russiaBiancaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        russiaBiancaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        russiaBiancaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        russiaBiancaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        russiaBiancaLabel.setName("russiaBiancaLabel"); // NOI18N
        mapPanel1.add(russiaBiancaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 70, 50));

        kazakistanLabel.setFont(resourceMap.getFont("iranLabel.font")); // NOI18N
        kazakistanLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kazakistanLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        kazakistanLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        kazakistanLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        kazakistanLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kazakistanLabel.setName("kazakistanLabel"); // NOI18N
        mapPanel1.add(kazakistanLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 340, 90, 140));

        ucrainaLabel.setFont(resourceMap.getFont("iranLabel.font")); // NOI18N
        ucrainaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ucrainaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        ucrainaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        ucrainaLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ucrainaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ucrainaLabel.setName("ucrainaLabel"); // NOI18N
        mapPanel1.add(ucrainaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 220, 60));

        georgiaLabel.setFont(resourceMap.getFont("iranLabel.font")); // NOI18N
        georgiaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        georgiaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        georgiaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        georgiaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        georgiaLabel.setName("georgiaLabel"); // NOI18N
        mapPanel1.add(georgiaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 490, 90, 50));

        bulgariaLabel.setFont(resourceMap.getFont("iranLabel.font")); // NOI18N
        bulgariaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bulgariaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        bulgariaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        bulgariaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bulgariaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bulgariaLabel.setName("bulgariaLabel"); // NOI18N
        mapPanel1.add(bulgariaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, 70, 40));

        romaniaLabel.setFont(resourceMap.getFont("iranLabel.font")); // NOI18N
        romaniaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        romaniaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        romaniaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        romaniaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        romaniaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        romaniaLabel.setName("romaniaLabel"); // NOI18N
        mapPanel1.add(romaniaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 80, 60));

        greciaLabel.setFont(resourceMap.getFont("iranLabel.font")); // NOI18N
        greciaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        greciaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        greciaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        greciaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        greciaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        greciaLabel.setName("greciaLabel"); // NOI18N
        mapPanel1.add(greciaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 500, 80, 120));

        yugoslaviaLabel.setFont(resourceMap.getFont("iranLabel.font")); // NOI18N
        yugoslaviaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yugoslaviaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        yugoslaviaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        yugoslaviaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        yugoslaviaLabel.setName("yugoslaviaLabel"); // NOI18N
        mapPanel1.add(yugoslaviaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, 60, 70));

        croaziaLabel.setFont(resourceMap.getFont("iranLabel.font")); // NOI18N
        croaziaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        croaziaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        croaziaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        croaziaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        croaziaLabel.setName("croaziaLabel"); // NOI18N
        mapPanel1.add(croaziaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 80, 50));

        slovacchiaLabel.setFont(resourceMap.getFont("iranLabel.font")); // NOI18N
        slovacchiaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slovacchiaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        slovacchiaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        slovacchiaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        slovacchiaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        slovacchiaLabel.setName("slovacchiaLabel"); // NOI18N
        mapPanel1.add(slovacchiaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 60, 40));

        ungheriaLabel.setFont(resourceMap.getFont("iranLabel.font")); // NOI18N
        ungheriaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ungheriaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        ungheriaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        ungheriaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        ungheriaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ungheriaLabel.setName("ungheriaLabel"); // NOI18N
        mapPanel1.add(ungheriaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 80, 40));

        poloniaLabel.setFont(resourceMap.getFont("iranLabel.font")); // NOI18N
        poloniaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        poloniaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        poloniaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        poloniaLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        poloniaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        poloniaLabel.setName("poloniaLabel"); // NOI18N
        mapPanel1.add(poloniaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 90, 50));

        danimarcaLabel.setFont(resourceMap.getFont("iranLabel.font")); // NOI18N
        danimarcaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        danimarcaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        danimarcaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        danimarcaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        danimarcaLabel.setName("danimarcaLabel"); // NOI18N
        mapPanel1.add(danimarcaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 50, 60));

        repubblicaCecaLabel.setFont(resourceMap.getFont("iranLabel.font")); // NOI18N
        repubblicaCecaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        repubblicaCecaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        repubblicaCecaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        repubblicaCecaLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        repubblicaCecaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        repubblicaCecaLabel.setName("repubblicaCecaLabel"); // NOI18N
        mapPanel1.add(repubblicaCecaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 90, 30));

        austriaLabel.setFont(resourceMap.getFont("iranLabel.font")); // NOI18N
        austriaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        austriaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        austriaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        austriaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        austriaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        austriaLabel.setName("austriaLabel"); // NOI18N
        mapPanel1.add(austriaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 60, 40));

        siriaLabel.setFont(resourceMap.getFont("iranLabel.font")); // NOI18N
        siriaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        siriaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        siriaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        siriaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        siriaLabel.setName("siriaLabel"); // NOI18N
        mapPanel1.add(siriaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 590, 80, 60));

        giordaniaLabel.setFont(resourceMap.getFont("iranLabel.font")); // NOI18N
        giordaniaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        giordaniaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        giordaniaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        giordaniaLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        giordaniaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        giordaniaLabel.setName("giordaniaLabel"); // NOI18N
        mapPanel1.add(giordaniaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 660, 60, 40));

        arabiaSauditaLabel.setFont(resourceMap.getFont("iranLabel.font")); // NOI18N
        arabiaSauditaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        arabiaSauditaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        arabiaSauditaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        arabiaSauditaLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        arabiaSauditaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        arabiaSauditaLabel.setName("arabiaSauditaLabel"); // NOI18N
        mapPanel1.add(arabiaSauditaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 660, 70, 40));

        tunisiaLabel.setFont(resourceMap.getFont("iranLabel.font")); // NOI18N
        tunisiaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tunisiaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        tunisiaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        tunisiaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tunisiaLabel.setName("tunisiaLabel"); // NOI18N
        mapPanel1.add(tunisiaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 590, 50, 70));

        maroccoLabel.setFont(resourceMap.getFont("iranLabel.font")); // NOI18N
        maroccoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maroccoLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        maroccoLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        maroccoLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        maroccoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        maroccoLabel.setName("maroccoLabel"); // NOI18N
        mapPanel1.add(maroccoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 600, 100, 100));

        libiaLabel.setFont(resourceMap.getFont("iranLabel.font")); // NOI18N
        libiaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        libiaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        libiaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        libiaLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        libiaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        libiaLabel.setName("libiaLabel"); // NOI18N
        mapPanel1.add(libiaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 650, 140, 50));

        algeriaLabel.setFont(resourceMap.getFont("iranLabel.font")); // NOI18N
        algeriaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        algeriaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        algeriaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        algeriaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        algeriaLabel.setName("algeriaLabel"); // NOI18N
        mapPanel1.add(algeriaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 580, 120, 120));

        portogalloLabel.setFont(resourceMap.getFont("iranLabel.font")); // NOI18N
        portogalloLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        portogalloLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        portogalloLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        portogalloLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        portogalloLabel.setName("portogalloLabel"); // NOI18N
        mapPanel1.add(portogalloLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, 50, 80));

        spagnaLabel.setFont(resourceMap.getFont("iranLabel.font")); // NOI18N
        spagnaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spagnaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        spagnaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        spagnaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        spagnaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        spagnaLabel.setName("spagnaLabel"); // NOI18N
        mapPanel1.add(spagnaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 130, 90));

        turchiaLabel.setFont(resourceMap.getFont("iranLabel.font")); // NOI18N
        turchiaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        turchiaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        turchiaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        turchiaLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        turchiaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        turchiaLabel.setName("turchiaLabel"); // NOI18N
        mapPanel1.add(turchiaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 500, 230, 70));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(resourceMap.getIcon("jLabel1.icon")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setName("jLabel1"); // NOI18N
        mapPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(mapPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>                        

  

  

   
  
    
    // Variables declaration - do not modify                     
    private javax.swing.JLabel algeriaLabel;
    private javax.swing.JLabel arabiaSauditaLabel;
    private javax.swing.JLabel austriaLabel;
    private javax.swing.JLabel bulgariaLabel;
    private javax.swing.JLabel croaziaLabel;
    private javax.swing.JLabel danimarcaLabel;
    private javax.swing.JLabel egittoLabel;
    private javax.swing.JLabel estoniaLabel;
    private javax.swing.JLabel finlandiaLabel;
    private javax.swing.JLabel franciaLabel;
    private javax.swing.JLabel georgiaLabel;
    private javax.swing.JLabel germaniaLabel;
    private javax.swing.JLabel giordaniaLabel;
    private javax.swing.JLabel greciaLabel;
    private javax.swing.JLabel iranLabel;
    private javax.swing.JLabel iraqLabel;
    private javax.swing.JLabel irlandaLabel;
    private javax.swing.JLabel islandaLabel;
    private javax.swing.JLabel italiaLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel kazakistanLabel;
    private javax.swing.JLabel libiaLabel;
    private javax.swing.JLabel lituaniaLabel;
    private virtualrisikoii.Map.europe.MapPanel mapPanel1;
    private javax.swing.JLabel maroccoLabel;
    private javax.swing.JLabel norvegiaLabel;
    private javax.swing.JLabel paesiBassiLabel;
    private javax.swing.JLabel poloniaLabel;
    private javax.swing.JLabel portogalloLabel;
    private javax.swing.JLabel regnoUnitoLabel;
    private javax.swing.JLabel repubblicaCecaLabel;
    private javax.swing.JLabel romaniaLabel;
    private javax.swing.JLabel russiaBiancaLabel;
    private javax.swing.JLabel russiaLabel;
    private javax.swing.JLabel siriaLabel;
    private javax.swing.JLabel slovacchiaLabel;
    private javax.swing.JLabel spagnaLabel;
    private javax.swing.JLabel sveziaLabel;
    private javax.swing.JLabel svizzeraLabel;
    private javax.swing.JLabel tunisiaLabel;
    private javax.swing.JLabel turchiaLabel;
    private javax.swing.JLabel ucrainaLabel;
    private javax.swing.JLabel ungheriaLabel;
    private javax.swing.JLabel yugoslaviaLabel;
    // End of variables declaration                   


}

