/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EuropeMapPanel.java
 *
 * Created on 20-apr-2011, 22.08.01
 */

package virtualrisikoii.Map.europe;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Iterator;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import services.CardListener;
import services.GameController;
import services.MapListener;
import services.TroopsSelector;
import services.VictoryListener;
import virtualrisikoii.ActionDialog;
import virtualrisikoii.EndGameFrame;
import virtualrisikoii.risiko.Giocatore;
import virtualrisikoii.risiko.JFrameCarte;
import virtualrisikoii.risiko.JFrameDadi;
import virtualrisikoii.risiko.dadiGui;

/**
 *
 * @author root
 */
public class EuropeMapPanel extends javax.swing.JPanel implements MapListener,TroopsSelector,VictoryListener,CardListener {

    private JLabel[] territoriLabels;
    private ImageIcon[] icons;


    private GameController gameController;


    /** Creates new form EuropeMapPanel */
    public EuropeMapPanel() {
        gameController=GameController.getInstance();
        gameController.setMapListener(this);
        gameController.setTroopsSelector(this);
        gameController.setVictoryListener(this);
        gameController.setCardListener(this);
        initComponents();
        territoriLabels=new JLabel[42];
        territoriLabels[0]=islandaLabel;
        territoriLabels[1]=irlandaLabel;
        territoriLabels[2]=regnoUnitoLabel;
        territoriLabels[3]=norvegiaLabel;
        territoriLabels[4]=sveziaLabel;
        territoriLabels[5]=finlandiaLabel;
        territoriLabels[6]=russiaLabel;
        territoriLabels[7]=estoniaLabel;
        territoriLabels[8]=lituaniaLabel;
        territoriLabels[9]=russiaBiancaLabel;
        territoriLabels[10]=ucrainaLabel;
        territoriLabels[11]=kazakistanLabel;
        territoriLabels[12]=georgiaLabel;
        territoriLabels[13]=turchiaLabel;
        territoriLabels[14]=iranLabel;
        territoriLabels[15]=iraqLabel;
        territoriLabels[16]=siriaLabel;
        territoriLabels[17]=arabiaSauditaLabel;
        territoriLabels[18]=giordaniaLabel;
        territoriLabels[19]=egittoLabel;
        territoriLabels[20]=libiaLabel;
        territoriLabels[21]=tunisiaLabel;
        territoriLabels[22]=algeriaLabel;
        territoriLabels[23]=maroccoLabel;
        territoriLabels[24]=portogalloLabel;
        territoriLabels[25]=spagnaLabel;
        territoriLabels[26]=franciaLabel;
        territoriLabels[27]=italiaLabel;
        territoriLabels[28]=svizzeraLabel;
        territoriLabels[29]=paesiBassiLabel;
        territoriLabels[30]=germaniaLabel;
        territoriLabels[31]=danimarcaLabel;
        territoriLabels[32]=poloniaLabel;
        territoriLabels[33]=repubblicaCecaLabel;
        territoriLabels[34]=austriaLabel;
        territoriLabels[35]=slovacchiaLabel;
        territoriLabels[36]=ungheriaLabel;
        territoriLabels[37]=croaziaLabel;
        territoriLabels[38]=yugoslaviaLabel;
        territoriLabels[39]=greciaLabel;
        territoriLabels[40]=bulgariaLabel;
        territoriLabels[41]=romaniaLabel;

        LabelSelector selector=new LabelSelector();
        for(int i=0;i<territoriLabels.length;i++){
            this.territoriLabels[i].addMouseListener(selector);
        }

        initIconPlayers();
        gameController.initMap();


        
    }

    public void initIconPlayers(){
        
        this.icons=new ImageIcon[6];
        icons[Giocatore.ROSSO]=new ImageIcon("src/virtualrisikoii/resources/tanks/rosso.png");
        icons[Giocatore.BLU]=new ImageIcon("src/virtualrisikoii/resources/tanks/blu.png");
        icons[Giocatore.GIALLO]=new ImageIcon("src/virtualrisikoii/resources/tanks/giallo.png");
        icons[Giocatore.NERO]=new ImageIcon("src/virtualrisikoii/resources/tanks/nero.png");
        icons[Giocatore.VERDE]=new ImageIcon("src/virtualrisikoii/resources/tanks/verde.png");
        icons[Giocatore.VIOLA]=new ImageIcon("src/virtualrisikoii/resources/tanks/viola.png");
       

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        mapPanel1 = new virtualrisikoii.Map.classical.MapPanel();
        iranLabel = new javax.swing.JLabel();
        egittoLabel = new javax.swing.JLabel();
        iraqLabel = new javax.swing.JLabel();
        franciaLabel = new javax.swing.JLabel();
        italiaLabel = new javax.swing.JLabel();
        svizzeraLabel = new javax.swing.JLabel();
        germaniaLabel = new javax.swing.JLabel();
        islandaLabel = new javax.swing.JLabel();
        sveziaLabel = new javax.swing.JLabel();
        paesiBassiLabel = new javax.swing.JLabel();
        irlandaLabel = new javax.swing.JLabel();
        norvegiaLabel = new javax.swing.JLabel();
        russiaLabel = new javax.swing.JLabel();
        finlandiaLabel = new javax.swing.JLabel();
        regnoUnitoLabel = new javax.swing.JLabel();
        estoniaLabel = new javax.swing.JLabel();
        lituaniaLabel = new javax.swing.JLabel();
        russiaBiancaLabel = new javax.swing.JLabel();
        kazakistanLabel = new javax.swing.JLabel();
        ucrainaLabel = new javax.swing.JLabel();
        georgiaLabel = new javax.swing.JLabel();
        bulgariaLabel = new javax.swing.JLabel();
        romaniaLabel = new javax.swing.JLabel();
        greciaLabel = new javax.swing.JLabel();
        yugoslaviaLabel = new javax.swing.JLabel();
        croaziaLabel = new javax.swing.JLabel();
        slovacchiaLabel = new javax.swing.JLabel();
        ungheriaLabel = new javax.swing.JLabel();
        poloniaLabel = new javax.swing.JLabel();
        danimarcaLabel = new javax.swing.JLabel();
        repubblicaCecaLabel = new javax.swing.JLabel();
        austriaLabel = new javax.swing.JLabel();
        siriaLabel = new javax.swing.JLabel();
        giordaniaLabel = new javax.swing.JLabel();
        arabiaSauditaLabel = new javax.swing.JLabel();
        tunisiaLabel = new javax.swing.JLabel();
        maroccoLabel = new javax.swing.JLabel();
        libiaLabel = new javax.swing.JLabel();
        algeriaLabel = new javax.swing.JLabel();
        portogalloLabel = new javax.swing.JLabel();
        spagnaLabel = new javax.swing.JLabel();
        turchiaLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setName("jLabel2"); // NOI18N

        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.BorderLayout());

        mapPanel1.setName("mapPanel1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(EuropeMapPanel.class);
        iranLabel.setFont(resourceMap.getFont("indiaLabel.font")); // NOI18N
        iranLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iranLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        iranLabel.setText(resourceMap.getString("indiaLabel.text")); // NOI18N
        iranLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iranLabel.setName("iranLabel"); // NOI18N
        mapPanel1.add(iranLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 570, 80, 80));

        egittoLabel.setFont(resourceMap.getFont("indiaLabel.font")); // NOI18N
        egittoLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        egittoLabel.setIcon(resourceMap.getIcon("scandinaviaLabel.icon")); // NOI18N
        egittoLabel.setText(resourceMap.getString("indiaLabel.text")); // NOI18N
        egittoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        egittoLabel.setName("egittoLabel"); // NOI18N
        mapPanel1.add(egittoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 680, 140, 20));

        iraqLabel.setFont(resourceMap.getFont("indiaLabel.font")); // NOI18N
        iraqLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iraqLabel.setIcon(resourceMap.getIcon("scandinaviaLabel.icon")); // NOI18N
        iraqLabel.setText(resourceMap.getString("indiaLabel.text")); // NOI18N
        iraqLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        iraqLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iraqLabel.setName("iraqLabel"); // NOI18N
        mapPanel1.add(iraqLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 600, 70, 70));

        franciaLabel.setFont(resourceMap.getFont("indiaLabel.font")); // NOI18N
        franciaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        franciaLabel.setIcon(resourceMap.getIcon("scandinaviaLabel.icon")); // NOI18N
        franciaLabel.setText(resourceMap.getString("indiaLabel.text")); // NOI18N
        franciaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        franciaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        franciaLabel.setName("franciaLabel"); // NOI18N
        mapPanel1.add(franciaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 120, 100));

        italiaLabel.setFont(resourceMap.getFont("indiaLabel.font")); // NOI18N
        italiaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        italiaLabel.setIcon(resourceMap.getIcon("scandinaviaLabel.icon")); // NOI18N
        italiaLabel.setText(resourceMap.getString("indiaLabel.text")); // NOI18N
        italiaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        italiaLabel.setName("italiaLabel"); // NOI18N
        mapPanel1.add(italiaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 130, 80));

        svizzeraLabel.setFont(resourceMap.getFont("indiaLabel.font")); // NOI18N
        svizzeraLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        svizzeraLabel.setIcon(resourceMap.getIcon("scandinaviaLabel.icon")); // NOI18N
        svizzeraLabel.setText(resourceMap.getString("indiaLabel.text")); // NOI18N
        svizzeraLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        svizzeraLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        svizzeraLabel.setName("svizzeraLabel"); // NOI18N
        mapPanel1.add(svizzeraLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 60, 40));

        germaniaLabel.setFont(resourceMap.getFont("indiaLabel.font")); // NOI18N
        germaniaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        germaniaLabel.setIcon(resourceMap.getIcon("scandinaviaLabel.icon")); // NOI18N
        germaniaLabel.setText(resourceMap.getString("indiaLabel.text")); // NOI18N
        germaniaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        germaniaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        germaniaLabel.setName("germaniaLabel"); // NOI18N
        mapPanel1.add(germaniaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 70, 90));

        islandaLabel.setFont(resourceMap.getFont("indiaLabel.font")); // NOI18N
        islandaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        islandaLabel.setIcon(resourceMap.getIcon("scandinaviaLabel.icon")); // NOI18N
        islandaLabel.setText(resourceMap.getString("indiaLabel.text")); // NOI18N
        islandaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        islandaLabel.setName("islandaLabel"); // NOI18N
        mapPanel1.add(islandaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 90, 100, 70));

        sveziaLabel.setFont(resourceMap.getFont("indiaLabel.font")); // NOI18N
        sveziaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sveziaLabel.setIcon(resourceMap.getIcon("scandinaviaLabel.icon")); // NOI18N
        sveziaLabel.setText(resourceMap.getString("indiaLabel.text")); // NOI18N
        sveziaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        sveziaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sveziaLabel.setName("sveziaLabel"); // NOI18N
        mapPanel1.add(sveziaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 70, 160));

        paesiBassiLabel.setFont(resourceMap.getFont("indiaLabel.font")); // NOI18N
        paesiBassiLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        paesiBassiLabel.setIcon(resourceMap.getIcon("scandinaviaLabel.icon")); // NOI18N
        paesiBassiLabel.setText(resourceMap.getString("indiaLabel.text")); // NOI18N
        paesiBassiLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paesiBassiLabel.setName("paesiBassiLabel"); // NOI18N
        mapPanel1.add(paesiBassiLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 50, 60));

        irlandaLabel.setFont(resourceMap.getFont("indiaLabel.font")); // NOI18N
        irlandaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        irlandaLabel.setIcon(resourceMap.getIcon("scandinaviaLabel.icon")); // NOI18N
        irlandaLabel.setText(resourceMap.getString("indiaLabel.text")); // NOI18N
        irlandaLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        irlandaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        irlandaLabel.setName("irlandaLabel"); // NOI18N
        mapPanel1.add(irlandaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 50, 50));

        norvegiaLabel.setFont(resourceMap.getFont("indiaLabel.font")); // NOI18N
        norvegiaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        norvegiaLabel.setIcon(resourceMap.getIcon("scandinaviaLabel.icon")); // NOI18N
        norvegiaLabel.setText(resourceMap.getString("indiaLabel.text")); // NOI18N
        norvegiaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        norvegiaLabel.setName("norvegiaLabel"); // NOI18N
        mapPanel1.add(norvegiaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 80, 80));

        russiaLabel.setFont(resourceMap.getFont("indiaLabel.font")); // NOI18N
        russiaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        russiaLabel.setIcon(resourceMap.getIcon("scandinaviaLabel.icon")); // NOI18N
        russiaLabel.setText(resourceMap.getString("indiaLabel.text")); // NOI18N
        russiaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        russiaLabel.setName("russiaLabel"); // NOI18N
        mapPanel1.add(russiaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 340, 310));

        finlandiaLabel.setFont(resourceMap.getFont("indiaLabel.font")); // NOI18N
        finlandiaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        finlandiaLabel.setIcon(resourceMap.getIcon("scandinaviaLabel.icon")); // NOI18N
        finlandiaLabel.setText(resourceMap.getString("indiaLabel.text")); // NOI18N
        finlandiaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        finlandiaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        finlandiaLabel.setName("finlandiaLabel"); // NOI18N
        mapPanel1.add(finlandiaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 80, 80));

        regnoUnitoLabel.setFont(resourceMap.getFont("indiaLabel.font")); // NOI18N
        regnoUnitoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regnoUnitoLabel.setIcon(resourceMap.getIcon("scandinaviaLabel.icon")); // NOI18N
        regnoUnitoLabel.setText(resourceMap.getString("indiaLabel.text")); // NOI18N
        regnoUnitoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regnoUnitoLabel.setName("regnoUnitoLabel"); // NOI18N
        mapPanel1.add(regnoUnitoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 80, 150));

        estoniaLabel.setFont(resourceMap.getFont("indiaLabel.font")); // NOI18N
        estoniaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        estoniaLabel.setIcon(resourceMap.getIcon("scandinaviaLabel.icon")); // NOI18N
        estoniaLabel.setText(resourceMap.getString("indiaLabel.text")); // NOI18N
        estoniaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        estoniaLabel.setName("estoniaLabel"); // NOI18N
        mapPanel1.add(estoniaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 90, 50));

        lituaniaLabel.setFont(resourceMap.getFont("indiaLabel.font")); // NOI18N
        lituaniaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lituaniaLabel.setIcon(resourceMap.getIcon("scandinaviaLabel.icon")); // NOI18N
        lituaniaLabel.setText(resourceMap.getString("indiaLabel.text")); // NOI18N
        lituaniaLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lituaniaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lituaniaLabel.setName("lituaniaLabel"); // NOI18N
        mapPanel1.add(lituaniaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 90, 30));

        russiaBiancaLabel.setFont(resourceMap.getFont("indiaLabel.font")); // NOI18N
        russiaBiancaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        russiaBiancaLabel.setIcon(resourceMap.getIcon("scandinaviaLabel.icon")); // NOI18N
        russiaBiancaLabel.setText(resourceMap.getString("indiaLabel.text")); // NOI18N
        russiaBiancaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        russiaBiancaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        russiaBiancaLabel.setName("russiaBiancaLabel"); // NOI18N
        mapPanel1.add(russiaBiancaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 70, 50));

        kazakistanLabel.setFont(resourceMap.getFont("indiaLabel.font")); // NOI18N
        kazakistanLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kazakistanLabel.setIcon(resourceMap.getIcon("scandinaviaLabel.icon")); // NOI18N
        kazakistanLabel.setText(resourceMap.getString("indiaLabel.text")); // NOI18N
        kazakistanLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        kazakistanLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kazakistanLabel.setName("kazakistanLabel"); // NOI18N
        mapPanel1.add(kazakistanLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 340, 90, 140));

        ucrainaLabel.setFont(resourceMap.getFont("indiaLabel.font")); // NOI18N
        ucrainaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ucrainaLabel.setIcon(resourceMap.getIcon("scandinaviaLabel.icon")); // NOI18N
        ucrainaLabel.setText(resourceMap.getString("indiaLabel.text")); // NOI18N
        ucrainaLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ucrainaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ucrainaLabel.setName("ucrainaLabel"); // NOI18N
        mapPanel1.add(ucrainaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 220, 60));

        georgiaLabel.setFont(resourceMap.getFont("indiaLabel.font")); // NOI18N
        georgiaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        georgiaLabel.setIcon(resourceMap.getIcon("scandinaviaLabel.icon")); // NOI18N
        georgiaLabel.setText(resourceMap.getString("indiaLabel.text")); // NOI18N
        georgiaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        georgiaLabel.setName("georgiaLabel"); // NOI18N
        mapPanel1.add(georgiaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 490, 90, 50));

        bulgariaLabel.setFont(resourceMap.getFont("indiaLabel.font")); // NOI18N
        bulgariaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bulgariaLabel.setIcon(resourceMap.getIcon("scandinaviaLabel.icon")); // NOI18N
        bulgariaLabel.setText(resourceMap.getString("indiaLabel.text")); // NOI18N
        bulgariaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bulgariaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bulgariaLabel.setName("bulgariaLabel"); // NOI18N
        mapPanel1.add(bulgariaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, 70, 40));

        romaniaLabel.setFont(resourceMap.getFont("indiaLabel.font")); // NOI18N
        romaniaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        romaniaLabel.setIcon(resourceMap.getIcon("scandinaviaLabel.icon")); // NOI18N
        romaniaLabel.setText(resourceMap.getString("indiaLabel.text")); // NOI18N
        romaniaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        romaniaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        romaniaLabel.setName("romaniaLabel"); // NOI18N
        mapPanel1.add(romaniaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 80, 60));

        greciaLabel.setFont(resourceMap.getFont("indiaLabel.font")); // NOI18N
        greciaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        greciaLabel.setIcon(resourceMap.getIcon("scandinaviaLabel.icon")); // NOI18N
        greciaLabel.setText(resourceMap.getString("indiaLabel.text")); // NOI18N
        greciaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        greciaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        greciaLabel.setName("greciaLabel"); // NOI18N
        mapPanel1.add(greciaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 500, 80, 120));

        yugoslaviaLabel.setFont(resourceMap.getFont("indiaLabel.font")); // NOI18N
        yugoslaviaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yugoslaviaLabel.setIcon(resourceMap.getIcon("scandinaviaLabel.icon")); // NOI18N
        yugoslaviaLabel.setText(resourceMap.getString("indiaLabel.text")); // NOI18N
        yugoslaviaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        yugoslaviaLabel.setName("yugoslaviaLabel"); // NOI18N
        mapPanel1.add(yugoslaviaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, 60, 70));

        croaziaLabel.setFont(resourceMap.getFont("indiaLabel.font")); // NOI18N
        croaziaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        croaziaLabel.setIcon(resourceMap.getIcon("scandinaviaLabel.icon")); // NOI18N
        croaziaLabel.setText(resourceMap.getString("indiaLabel.text")); // NOI18N
        croaziaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        croaziaLabel.setName("croaziaLabel"); // NOI18N
        mapPanel1.add(croaziaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 80, 50));

        slovacchiaLabel.setFont(resourceMap.getFont("slovacchiaLabel.font")); // NOI18N
        slovacchiaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        slovacchiaLabel.setIcon(resourceMap.getIcon("scandinaviaLabel.icon")); // NOI18N
        slovacchiaLabel.setText(resourceMap.getString("slovacchiaLabel.text")); // NOI18N
        slovacchiaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        slovacchiaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        slovacchiaLabel.setName("slovacchiaLabel"); // NOI18N
        mapPanel1.add(slovacchiaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 50, 40));

        ungheriaLabel.setFont(resourceMap.getFont("indiaLabel.font")); // NOI18N
        ungheriaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ungheriaLabel.setIcon(resourceMap.getIcon("scandinaviaLabel.icon")); // NOI18N
        ungheriaLabel.setText(resourceMap.getString("indiaLabel.text")); // NOI18N
        ungheriaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        ungheriaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ungheriaLabel.setName("ungheriaLabel"); // NOI18N
        mapPanel1.add(ungheriaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 80, 40));

        poloniaLabel.setFont(resourceMap.getFont("indiaLabel.font")); // NOI18N
        poloniaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        poloniaLabel.setIcon(resourceMap.getIcon("scandinaviaLabel.icon")); // NOI18N
        poloniaLabel.setText(resourceMap.getString("indiaLabel.text")); // NOI18N
        poloniaLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        poloniaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        poloniaLabel.setName("poloniaLabel"); // NOI18N
        mapPanel1.add(poloniaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 90, 50));

        danimarcaLabel.setFont(resourceMap.getFont("indiaLabel.font")); // NOI18N
        danimarcaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        danimarcaLabel.setIcon(resourceMap.getIcon("scandinaviaLabel.icon")); // NOI18N
        danimarcaLabel.setText(resourceMap.getString("indiaLabel.text")); // NOI18N
        danimarcaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        danimarcaLabel.setName("danimarcaLabel"); // NOI18N
        mapPanel1.add(danimarcaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 50, 60));

        repubblicaCecaLabel.setFont(resourceMap.getFont("indiaLabel.font")); // NOI18N
        repubblicaCecaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        repubblicaCecaLabel.setIcon(resourceMap.getIcon("scandinaviaLabel.icon")); // NOI18N
        repubblicaCecaLabel.setText(resourceMap.getString("indiaLabel.text")); // NOI18N
        repubblicaCecaLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        repubblicaCecaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        repubblicaCecaLabel.setName("repubblicaCecaLabel"); // NOI18N
        mapPanel1.add(repubblicaCecaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 90, 20));

        austriaLabel.setFont(resourceMap.getFont("indiaLabel.font")); // NOI18N
        austriaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        austriaLabel.setIcon(resourceMap.getIcon("scandinaviaLabel.icon")); // NOI18N
        austriaLabel.setText(resourceMap.getString("indiaLabel.text")); // NOI18N
        austriaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        austriaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        austriaLabel.setName("austriaLabel"); // NOI18N
        mapPanel1.add(austriaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 60, 40));

        siriaLabel.setFont(resourceMap.getFont("indiaLabel.font")); // NOI18N
        siriaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        siriaLabel.setIcon(resourceMap.getIcon("scandinaviaLabel.icon")); // NOI18N
        siriaLabel.setText(resourceMap.getString("indiaLabel.text")); // NOI18N
        siriaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        siriaLabel.setName("siriaLabel"); // NOI18N
        mapPanel1.add(siriaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 590, 80, 60));

        giordaniaLabel.setFont(resourceMap.getFont("indiaLabel.font")); // NOI18N
        giordaniaLabel.setIcon(resourceMap.getIcon("scandinaviaLabel.icon")); // NOI18N
        giordaniaLabel.setText(resourceMap.getString("indiaLabel.text")); // NOI18N
        giordaniaLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        giordaniaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        giordaniaLabel.setName("giordaniaLabel"); // NOI18N
        mapPanel1.add(giordaniaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 660, 50, 40));

        arabiaSauditaLabel.setFont(resourceMap.getFont("indiaLabel.font")); // NOI18N
        arabiaSauditaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        arabiaSauditaLabel.setIcon(resourceMap.getIcon("scandinaviaLabel.icon")); // NOI18N
        arabiaSauditaLabel.setText(resourceMap.getString("indiaLabel.text")); // NOI18N
        arabiaSauditaLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        arabiaSauditaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        arabiaSauditaLabel.setName("arabiaSauditaLabel"); // NOI18N
        mapPanel1.add(arabiaSauditaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 660, 70, 40));

        tunisiaLabel.setFont(resourceMap.getFont("indiaLabel.font")); // NOI18N
        tunisiaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tunisiaLabel.setIcon(resourceMap.getIcon("scandinaviaLabel.icon")); // NOI18N
        tunisiaLabel.setText(resourceMap.getString("indiaLabel.text")); // NOI18N
        tunisiaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tunisiaLabel.setName("tunisiaLabel"); // NOI18N
        mapPanel1.add(tunisiaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 590, 50, 70));

        maroccoLabel.setFont(resourceMap.getFont("indiaLabel.font")); // NOI18N
        maroccoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maroccoLabel.setIcon(resourceMap.getIcon("scandinaviaLabel.icon")); // NOI18N
        maroccoLabel.setText(resourceMap.getString("indiaLabel.text")); // NOI18N
        maroccoLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        maroccoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        maroccoLabel.setName("maroccoLabel"); // NOI18N
        mapPanel1.add(maroccoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 600, 100, 100));

        libiaLabel.setFont(resourceMap.getFont("indiaLabel.font")); // NOI18N
        libiaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        libiaLabel.setIcon(resourceMap.getIcon("scandinaviaLabel.icon")); // NOI18N
        libiaLabel.setText(resourceMap.getString("indiaLabel.text")); // NOI18N
        libiaLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        libiaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        libiaLabel.setName("libiaLabel"); // NOI18N
        mapPanel1.add(libiaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 650, 140, 50));

        algeriaLabel.setFont(resourceMap.getFont("indiaLabel.font")); // NOI18N
        algeriaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        algeriaLabel.setIcon(resourceMap.getIcon("scandinaviaLabel.icon")); // NOI18N
        algeriaLabel.setText(resourceMap.getString("indiaLabel.text")); // NOI18N
        algeriaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        algeriaLabel.setName("algeriaLabel"); // NOI18N
        mapPanel1.add(algeriaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 580, 120, 120));

        portogalloLabel.setFont(resourceMap.getFont("indiaLabel.font")); // NOI18N
        portogalloLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        portogalloLabel.setIcon(resourceMap.getIcon("scandinaviaLabel.icon")); // NOI18N
        portogalloLabel.setText(resourceMap.getString("indiaLabel.text")); // NOI18N
        portogalloLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        portogalloLabel.setName("portogalloLabel"); // NOI18N
        mapPanel1.add(portogalloLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, 50, 80));

        spagnaLabel.setFont(resourceMap.getFont("indiaLabel.font")); // NOI18N
        spagnaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spagnaLabel.setIcon(resourceMap.getIcon("scandinaviaLabel.icon")); // NOI18N
        spagnaLabel.setText(resourceMap.getString("indiaLabel.text")); // NOI18N
        spagnaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        spagnaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        spagnaLabel.setName("spagnaLabel"); // NOI18N
        mapPanel1.add(spagnaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 130, 90));

        turchiaLabel.setFont(resourceMap.getFont("indiaLabel.font")); // NOI18N
        turchiaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        turchiaLabel.setIcon(resourceMap.getIcon("scandinaviaLabel.icon")); // NOI18N
        turchiaLabel.setText(resourceMap.getString("indiaLabel.text")); // NOI18N
        turchiaLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        turchiaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        turchiaLabel.setName("turchiaLabel"); // NOI18N
        mapPanel1.add(turchiaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 500, 230, 70));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(resourceMap.getIcon("jLabel1.icon")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setName("jLabel1"); // NOI18N
        mapPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(mapPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void makeAction(JLabel label,java.awt.event.MouseEvent event){ 
       /* if(!gameController.canMove()){
            return;
        }

        int id=this.getLabelID(label);
        this.gameController.makeAction(id);*/

        if(!gameController.canMove()){
            return;
        }
        int idTerritorio=this.getLabelID(label);

        if(gameController.isInInizializzazione()){
            gameController.assegnaUnitaInInizializzazione(idTerritorio);
            return;
        }

        if(gameController.haTruppe()){
            gameController.assegnaUnita(idTerritorio);
            return;
        }

        if(gameController.getFirstSelectionID()==-1){
            gameController.makeFirstSelection(idTerritorio);
            return;
        }

        gameController.makeSecondSelection(idTerritorio);
        int firstSelection=gameController.getFirstSelectionID();
        int secondSelection=gameController.getSecondSelectionID();

        if(firstSelection!=-1 && secondSelection!=-1){
            if(!gameController.makeAttack(firstSelection, secondSelection)){
                gameController.makeSpostamento(firstSelection, secondSelection);
            }
        }

        gameController.resetActionData();
        
    }

   
       
   

   public int selectTroops(boolean isAttacco,int maxTruppe,int daTerritorio,int aTerritorio){
       String title="Spostamento ";
       
       if(isAttacco){
           title="Attacco";
           
       }



       ActionDialog dialog=new ActionDialog(null, true);
       dialog.setTitle(title);
       dialog.getDaTerritorioTextName().setText(this.territoriLabels[daTerritorio].getToolTipText());
       dialog.getaTerritorioTextName().setText(this.territoriLabels[aTerritorio].getToolTipText());
       dialog.setMaximum(maxTruppe);
       dialog.setMinimum(1);
       dialog.setValue(maxTruppe/2);
       dialog.setVisible(true);

       if(dialog.getReturnStatus()==ActionDialog.RET_OK){
           return Integer.parseInt(dialog.getNumeroTruppeText().getText());
       }

       return -1;
   }
   
   private int getLabelID(JLabel label){
       int size=this.territoriLabels.length;
       boolean trovato=false;
       int i;
       for(i=0;i<size&&!trovato;i++){
           trovato=(label==territoriLabels[i]);
       }
       return i-1;
   }

   /* public void updateAppliance(int troops_number, int region) {

        Territorio territorio=this.tavolo.getMappa().getTerritorio(region);
        String message="Il "+territorio.getOccupante().getNome()+" posiziona "+troops_number+" in "+territorio.getNome();
        this.informationPanel.appendActionInHistory(message);
        System.out.println("ricevuto messaggio di appliance per territorio "+territorio.getNome()+" di "+troops_number+" unita");
        if(tavolo.assegnaUnita(troops_number, territorio)){
            this.territoriLabels[region].setText(Integer.toString(territorio.getNumeroUnita()));
            this.informationPanel.updateDatiGiocatore(territorio.getOccupante());
        }else{
            System.out.println("errore comunicazione appliance");
            
        }
        //showInfo("Disposizione", message);
    }*/

 /*   public void updateAttack(int troops_number, int from, int to) {
        Territorio fromTerritorio=this.tavolo.getMappa().getTerritorio(from);
        Territorio toTerritorio=this.tavolo.getMappa().getTerritorio(to);
        Giocatore  attaccante=fromTerritorio.getOccupante();
        Giocatore difensore=toTerritorio.getOccupante();
        Azione azione=tavolo.preparaAttacco(fromTerritorio, toTerritorio);
        VirtualRisikoIIEndGameBox endGameBox;
        System.out.println("ricevuto messaggio di attacco da territorio "+fromTerritorio.getNome()+"a territorio "+toTerritorio.getNome()+" con "+troops_number+" unita");
            if(azione!=null){
                azione.setNumeroTruppe(troops_number);
                tavolo.eseguiAttacco((Attacco)azione);

                this.informationPanel.appendActionInHistory(azione.toString());
                this.setLabel(azione.getDaTerritorio());
                this.setLabel(azione.getaTerritorio());
                String message="Il "+fromTerritorio.getOccupante().getNome()+" attacca da "+fromTerritorio.getNome()+"\n"+" a "+toTerritorio.getNome()+"\n"+" con "+troops_number+" unita"+
                        "attacco : ";
                if(azione.isAttacco()){

                    //variabili per i dati di Luigi
                    int [] att={0,0,0};
                    int [] dif={0,0,0};

                    int[] a=((Attacco)azione).getPunteggio();
                    String s="";
                    for(int i=0;i<a.length;i++){
                        s=s+" - "+Integer.toString(a[i]);
                        att[i]=a[i];
                    }
                    this.informationPanel.appendActionInHistory(s);
                    message=message+s+"\n"+"difesa : " ;
                    a=((Attacco)azione).getPunteggioAvversario();
                     s="";
                    for(int i=0;i<a.length;i++){
                        s=s+" - "+Integer.toString(a[i]);
                        dif[i]=a[i];
                    }
                     message=message+s;
                    this.informationPanel.appendActionInHistory(s);

                    //lancia il panel di Luigi
                    new dadiGui("Attacco da "+azione.getDaTerritorio().getNome()+" a "+azione.getaTerritorio().getNome(),att[0],att[1],att[2],dif[0],dif[1],dif[2],attaccante.getID(),difensore.getID()).setVisible(true);
                

                }

                //azione diversa da null::controllare stato obiettivi
                if(this.tavolo.controllaObiettivoGiocatore(this.tavolo.getGiocatoreCorrente())){

                   this.showEndFrame(tavolo.getGiocatori(), tavolo.getGiocatoreCorrente());
                }

            }else{
            System.out.println("errore comunicazione attacco");
            
        }

    }*/

 /*   public void updateMovement(int troops_number, int from, int to) {
        Territorio fromTerritorio=this.tavolo.getMappa().getTerritorio(from);
        Territorio toTerritorio=this.tavolo.getMappa().getTerritorio(to);
        System.out.println("Spostamento :Il "+tavolo.getGiocatoreCorrente()+" sposta da "+fromTerritorio.getNome()+" a "+toTerritorio.getNome()+" con "+troops_number+" unita");
        Azione azione=tavolo.preparaSpostamento(fromTerritorio, toTerritorio);
        VirtualRisikoIIEndGameBox endGameBox;
        if(azione!=null){
            azione.setNumeroTruppe(troops_number);
            tavolo.eseguiSpostamento((Spostamento) azione);

                this.informationPanel.appendActionInHistory(azione.toString());
                this.setLabel(azione.getDaTerritorio());
                this.setLabel(azione.getaTerritorio());

                

                //azione diversa da null::controllare stato obiettivi
                if(this.tavolo.controllaObiettivoGiocatore(this.tavolo.getGiocatoreCorrente())){

                    this.showEndFrame(tavolo.getGiocatori(), this.tavolo.getGiocatoreCorrente());
                }

            }

    }*/

    public void notifyVictory(List<Giocatore> giocatori,Giocatore vincitore){
        EndGameFrame frame=new EndGameFrame();
        frame.setVincitore(vincitore);
        Iterator<Giocatore> iter=giocatori.iterator();
        while(iter.hasNext())
            frame.setPunteggio(iter.next());
        frame.setVisible(true);
        //this.setVisible(false);
    }

    public void setLabelAttributes(int idLabel, int troopNumber, int idIcon) {
       JLabel label=this.territoriLabels[idLabel];
       label.setText(Integer.toString(troopNumber));
       label.setIcon(icons[idIcon]);
    }

    public void notifyAttacco(String string, int i, int i0, int i1, int i2, int i3, int i4, int iD, int iD0) {
        JFrameDadi jfd= new JFrameDadi(string,i,i0,i1,i2,i3,i4,iD,iD0);
        jfd.avviaDadi();
        jfd.setVisible(true);

    }

    public void notifyCard(int tipo, String territorio) {
        JFrameCarte jfc = new JFrameCarte(tipo, territorio);
        jfc.avviaCarta();
        jfc.setVisible(true);

          }

   /* public void updateChangeCards(int card1, int card2, int card3) {

        Tavolo tavolo=Tavolo.getInstance();
        Giocatore g=tavolo.getGiocatoreCorrente();
        Carta c1=g.getCarta(card1);
        Carta c2=g.getCarta(card2);
        Carta c3=g.getCarta(card3);
        int rinforzi=Rinforzo.getRinfornzo(g, c1, c2, c3, tavolo.getMappa());
        g.setNumeroTruppe(g.getNumeroTruppe()+rinforzi);
        System.out.println("Ricevuta cambio dal "+g.getNome()+" con "+c1.getTerritorio().getNome()+" "+c2.getTerritorio().getNome()+" "+c3.getTerritorio().getNome());
        this.informationPanel.updateDatiGiocatore(g);
        List<Carta> carte=tavolo.getCarte();
        carte.add(c1);
        carte.add(c2);
        carte.add(c3);

    }*/

   private class LabelSelector extends MouseAdapter{
       public void mouseClicked(MouseEvent e){
           makeAction((JLabel)e.getSource(),e);
       }
   }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel algeriaLabel;
    private javax.swing.JLabel arabiaSauditaLabel;
    private javax.swing.JLabel austriaLabel;
    private javax.swing.JLabel bulgariaLabel;
    private javax.swing.JLabel croaziaLabel;
    private javax.swing.JLabel danimarcaLabel;
    private javax.swing.JLabel egittoLabel;
    private javax.swing.JLabel estoniaLabel;
    private javax.swing.JLabel finlandiaLabel;
    private javax.swing.JLabel franciaLabel;
    private javax.swing.JLabel georgiaLabel;
    private javax.swing.JLabel germaniaLabel;
    private javax.swing.JLabel giordaniaLabel;
    private javax.swing.JLabel greciaLabel;
    private javax.swing.JLabel iranLabel;
    private javax.swing.JLabel iraqLabel;
    private javax.swing.JLabel irlandaLabel;
    private javax.swing.JLabel islandaLabel;
    private javax.swing.JLabel italiaLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel kazakistanLabel;
    private javax.swing.JLabel libiaLabel;
    private javax.swing.JLabel lituaniaLabel;
    private virtualrisikoii.Map.classical.MapPanel mapPanel1;
    private javax.swing.JLabel maroccoLabel;
    private javax.swing.JLabel norvegiaLabel;
    private javax.swing.JLabel paesiBassiLabel;
    private javax.swing.JLabel poloniaLabel;
    private javax.swing.JLabel portogalloLabel;
    private javax.swing.JLabel regnoUnitoLabel;
    private javax.swing.JLabel repubblicaCecaLabel;
    private javax.swing.JLabel romaniaLabel;
    private javax.swing.JLabel russiaBiancaLabel;
    private javax.swing.JLabel russiaLabel;
    private javax.swing.JLabel siriaLabel;
    private javax.swing.JLabel slovacchiaLabel;
    private javax.swing.JLabel spagnaLabel;
    private javax.swing.JLabel sveziaLabel;
    private javax.swing.JLabel svizzeraLabel;
    private javax.swing.JLabel tunisiaLabel;
    private javax.swing.JLabel turchiaLabel;
    private javax.swing.JLabel ucrainaLabel;
    private javax.swing.JLabel ungheriaLabel;
    private javax.swing.JLabel yugoslaviaLabel;
    // End of variables declaration//GEN-END:variables


}
