/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EuropeMapPanel.java
 *
 * Created on 20-apr-2011, 22.08.01
 */

package virtualrisikoii.Map.europe;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Iterator;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import services.CardListener;
import services.GameController;
import services.MapListener;
import services.TroopsSelector;
import services.VictoryListener;
import virtualrisikoii.ActionDialog;
import virtualrisikoii.EndGameFrame;
import virtualrisikoii.XMapPanel;
import virtualrisikoii.risiko.Giocatore;
import virtualrisikoii.risiko.JFrameCarte;
import virtualrisikoii.risiko.JFrameDadi;
import virtualrisikoii.risiko.dadiGui;

/**
 *
 * @author root
 */
public class EuropeMapPanel extends XMapPanel {

    


    /** Creates new form EuropeMapPanel */
    public EuropeMapPanel() {
        gameController=GameController.getInstance();
        gameController.setMapListener(this);
        gameController.setTroopsSelector(this);
        gameController.setVictoryListener(this);
        gameController.setCardListener(this);
        initComponents();
        territoriLabels=new JLabel[42];
        territoriLabels[0]=islandaLabel;
        territoriLabels[1]=irlandaLabel;
        territoriLabels[2]=regnoUnitoLabel;
        territoriLabels[3]=norvegiaLabel;
        territoriLabels[4]=sveziaLabel;
        territoriLabels[5]=finlandiaLabel;
        territoriLabels[6]=russiaLabel;
        territoriLabels[7]=estoniaLabel;
        territoriLabels[8]=lituaniaLabel;
        territoriLabels[9]=russiaBiancaLabel;
        territoriLabels[10]=ucrainaLabel;
        territoriLabels[11]=kazakistanLabel;
        territoriLabels[12]=georgiaLabel;
        territoriLabels[13]=turchiaLabel;
        territoriLabels[14]=iranLabel;
        territoriLabels[15]=iraqLabel;
        territoriLabels[16]=siriaLabel;
        territoriLabels[17]=arabiaSauditaLabel;
        territoriLabels[18]=giordaniaLabel;
        territoriLabels[19]=egittoLabel;
        territoriLabels[20]=libiaLabel;
        territoriLabels[21]=tunisiaLabel;
        territoriLabels[22]=algeriaLabel;
        territoriLabels[23]=maroccoLabel;
        territoriLabels[24]=portogalloLabel;
        territoriLabels[25]=spagnaLabel;
        territoriLabels[26]=franciaLabel;
        territoriLabels[27]=italiaLabel;
        territoriLabels[28]=svizzeraLabel;
        territoriLabels[29]=paesiBassiLabel;
        territoriLabels[30]=germaniaLabel;
        territoriLabels[31]=danimarcaLabel;
        territoriLabels[32]=poloniaLabel;
        territoriLabels[33]=repubblicaCecaLabel;
        territoriLabels[34]=austriaLabel;
        territoriLabels[35]=slovacchiaLabel;
        territoriLabels[36]=ungheriaLabel;
        territoriLabels[37]=croaziaLabel;
        territoriLabels[38]=yugoslaviaLabel;
        territoriLabels[39]=greciaLabel;
        territoriLabels[40]=bulgariaLabel;
        territoriLabels[41]=romaniaLabel;

        LabelSelector selector=new LabelSelector();
        for(int i=0;i<territoriLabels.length;i++){
            this.territoriLabels[i].addMouseListener(selector);
        }

        initIconPlayers();
        gameController.initMap();


        
    }

   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        mapPanel1 = new virtualrisikoii.Map.europe.MapPanel();
        iranLabel = new javax.swing.JLabel();
        egittoLabel = new javax.swing.JLabel();
        iraqLabel = new javax.swing.JLabel();
        franciaLabel = new javax.swing.JLabel();
        italiaLabel = new javax.swing.JLabel();
        svizzeraLabel = new javax.swing.JLabel();
        germaniaLabel = new javax.swing.JLabel();
        islandaLabel = new javax.swing.JLabel();
        sveziaLabel = new javax.swing.JLabel();
        paesiBassiLabel = new javax.swing.JLabel();
        irlandaLabel = new javax.swing.JLabel();
        norvegiaLabel = new javax.swing.JLabel();
        russiaLabel = new javax.swing.JLabel();
        finlandiaLabel = new javax.swing.JLabel();
        regnoUnitoLabel = new javax.swing.JLabel();
        estoniaLabel = new javax.swing.JLabel();
        lituaniaLabel = new javax.swing.JLabel();
        russiaBiancaLabel = new javax.swing.JLabel();
        kazakistanLabel = new javax.swing.JLabel();
        ucrainaLabel = new javax.swing.JLabel();
        georgiaLabel = new javax.swing.JLabel();
        bulgariaLabel = new javax.swing.JLabel();
        romaniaLabel = new javax.swing.JLabel();
        greciaLabel = new javax.swing.JLabel();
        yugoslaviaLabel = new javax.swing.JLabel();
        croaziaLabel = new javax.swing.JLabel();
        slovacchiaLabel = new javax.swing.JLabel();
        ungheriaLabel = new javax.swing.JLabel();
        poloniaLabel = new javax.swing.JLabel();
        danimarcaLabel = new javax.swing.JLabel();
        repubblicaCecaLabel = new javax.swing.JLabel();
        austriaLabel = new javax.swing.JLabel();
        siriaLabel = new javax.swing.JLabel();
        giordaniaLabel = new javax.swing.JLabel();
        arabiaSauditaLabel = new javax.swing.JLabel();
        tunisiaLabel = new javax.swing.JLabel();
        maroccoLabel = new javax.swing.JLabel();
        libiaLabel = new javax.swing.JLabel();
        algeriaLabel = new javax.swing.JLabel();
        portogalloLabel = new javax.swing.JLabel();
        spagnaLabel = new javax.swing.JLabel();
        turchiaLabel = new javax.swing.JLabel();

        jLabel2.setName("jLabel2"); // NOI18N

        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.BorderLayout());

        mapPanel1.setName("mapPanel1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(EuropeMapPanel.class);
        iranLabel.setFont(resourceMap.getFont("poloniaLabel.font")); // NOI18N
        iranLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iranLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        iranLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        iranLabel.setToolTipText(resourceMap.getString("iranLabel.toolTipText")); // NOI18N
        iranLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        iranLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iranLabel.setName("iranLabel"); // NOI18N
        mapPanel1.add(iranLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 530, 80, 70));

        egittoLabel.setFont(resourceMap.getFont("poloniaLabel.font")); // NOI18N
        egittoLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        egittoLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        egittoLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        egittoLabel.setToolTipText(resourceMap.getString("egittoLabel.toolTipText")); // NOI18N
        egittoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        egittoLabel.setName("egittoLabel"); // NOI18N
        mapPanel1.add(egittoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 650, 130, 30));

        iraqLabel.setFont(resourceMap.getFont("poloniaLabel.font")); // NOI18N
        iraqLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iraqLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        iraqLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        iraqLabel.setToolTipText(resourceMap.getString("iraqLabel.toolTipText")); // NOI18N
        iraqLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        iraqLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iraqLabel.setName("iraqLabel"); // NOI18N
        mapPanel1.add(iraqLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 570, 60, 60));

        franciaLabel.setFont(resourceMap.getFont("poloniaLabel.font")); // NOI18N
        franciaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        franciaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        franciaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        franciaLabel.setToolTipText(resourceMap.getString("franciaLabel.toolTipText")); // NOI18N
        franciaLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        franciaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        franciaLabel.setName("franciaLabel"); // NOI18N
        mapPanel1.add(franciaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 90, 90));

        italiaLabel.setFont(resourceMap.getFont("poloniaLabel.font")); // NOI18N
        italiaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        italiaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        italiaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        italiaLabel.setToolTipText(resourceMap.getString("italiaLabel.toolTipText")); // NOI18N
        italiaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        italiaLabel.setName("italiaLabel"); // NOI18N
        mapPanel1.add(italiaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 130, 100));

        svizzeraLabel.setFont(resourceMap.getFont("poloniaLabel.font")); // NOI18N
        svizzeraLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        svizzeraLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        svizzeraLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        svizzeraLabel.setToolTipText(resourceMap.getString("svizzeraLabel.toolTipText")); // NOI18N
        svizzeraLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        svizzeraLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        svizzeraLabel.setName("svizzeraLabel"); // NOI18N
        mapPanel1.add(svizzeraLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 70, 40));

        germaniaLabel.setFont(resourceMap.getFont("poloniaLabel.font")); // NOI18N
        germaniaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        germaniaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        germaniaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        germaniaLabel.setToolTipText(resourceMap.getString("germaniaLabel.toolTipText")); // NOI18N
        germaniaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        germaniaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        germaniaLabel.setName("germaniaLabel"); // NOI18N
        mapPanel1.add(germaniaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 60, 90));

        islandaLabel.setFont(resourceMap.getFont("poloniaLabel.font")); // NOI18N
        islandaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        islandaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        islandaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        islandaLabel.setToolTipText(resourceMap.getString("islandaLabel.toolTipText")); // NOI18N
        islandaLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        islandaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        islandaLabel.setName("islandaLabel"); // NOI18N
        mapPanel1.add(islandaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 90, 50));

        sveziaLabel.setFont(resourceMap.getFont("poloniaLabel.font")); // NOI18N
        sveziaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sveziaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        sveziaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        sveziaLabel.setToolTipText(resourceMap.getString("sveziaLabel.toolTipText")); // NOI18N
        sveziaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        sveziaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sveziaLabel.setName("sveziaLabel"); // NOI18N
        mapPanel1.add(sveziaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 80, 160));

        paesiBassiLabel.setFont(resourceMap.getFont("poloniaLabel.font")); // NOI18N
        paesiBassiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paesiBassiLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        paesiBassiLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        paesiBassiLabel.setToolTipText(resourceMap.getString("paesiBassiLabel.toolTipText")); // NOI18N
        paesiBassiLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paesiBassiLabel.setName("paesiBassiLabel"); // NOI18N
        mapPanel1.add(paesiBassiLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 50, 60));

        irlandaLabel.setFont(resourceMap.getFont("poloniaLabel.font")); // NOI18N
        irlandaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        irlandaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        irlandaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        irlandaLabel.setToolTipText(resourceMap.getString("irlandaLabel.toolTipText")); // NOI18N
        irlandaLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        irlandaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        irlandaLabel.setName("irlandaLabel"); // NOI18N
        mapPanel1.add(irlandaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 50, 50));

        norvegiaLabel.setFont(resourceMap.getFont("poloniaLabel.font")); // NOI18N
        norvegiaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        norvegiaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        norvegiaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        norvegiaLabel.setToolTipText(resourceMap.getString("norvegiaLabel.toolTipText")); // NOI18N
        norvegiaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        norvegiaLabel.setName("norvegiaLabel"); // NOI18N
        mapPanel1.add(norvegiaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 80, 80));

        russiaLabel.setFont(resourceMap.getFont("poloniaLabel.font")); // NOI18N
        russiaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        russiaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        russiaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        russiaLabel.setToolTipText(resourceMap.getString("russiaLabel.toolTipText")); // NOI18N
        russiaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        russiaLabel.setName("russiaLabel"); // NOI18N
        mapPanel1.add(russiaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 330, 280));

        finlandiaLabel.setFont(resourceMap.getFont("poloniaLabel.font")); // NOI18N
        finlandiaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        finlandiaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        finlandiaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        finlandiaLabel.setToolTipText(resourceMap.getString("finlandiaLabel.toolTipText")); // NOI18N
        finlandiaLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        finlandiaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        finlandiaLabel.setName("finlandiaLabel"); // NOI18N
        mapPanel1.add(finlandiaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 80, 100));

        regnoUnitoLabel.setFont(resourceMap.getFont("poloniaLabel.font")); // NOI18N
        regnoUnitoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regnoUnitoLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        regnoUnitoLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        regnoUnitoLabel.setToolTipText(resourceMap.getString("regnoUnitoLabel.toolTipText")); // NOI18N
        regnoUnitoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regnoUnitoLabel.setName("regnoUnitoLabel"); // NOI18N
        mapPanel1.add(regnoUnitoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 80, 150));

        estoniaLabel.setFont(resourceMap.getFont("poloniaLabel.font")); // NOI18N
        estoniaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        estoniaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        estoniaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        estoniaLabel.setToolTipText(resourceMap.getString("estoniaLabel.toolTipText")); // NOI18N
        estoniaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        estoniaLabel.setName("estoniaLabel"); // NOI18N
        mapPanel1.add(estoniaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 70, 40));

        lituaniaLabel.setFont(resourceMap.getFont("poloniaLabel.font")); // NOI18N
        lituaniaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lituaniaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        lituaniaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        lituaniaLabel.setToolTipText(resourceMap.getString("lituaniaLabel.toolTipText")); // NOI18N
        lituaniaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lituaniaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lituaniaLabel.setName("lituaniaLabel"); // NOI18N
        mapPanel1.add(lituaniaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 90, 30));

        russiaBiancaLabel.setFont(resourceMap.getFont("poloniaLabel.font")); // NOI18N
        russiaBiancaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        russiaBiancaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        russiaBiancaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        russiaBiancaLabel.setToolTipText(resourceMap.getString("russiaBiancaLabel.toolTipText")); // NOI18N
        russiaBiancaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        russiaBiancaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        russiaBiancaLabel.setName("russiaBiancaLabel"); // NOI18N
        mapPanel1.add(russiaBiancaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 70, 50));

        kazakistanLabel.setFont(resourceMap.getFont("poloniaLabel.font")); // NOI18N
        kazakistanLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kazakistanLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        kazakistanLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        kazakistanLabel.setToolTipText(resourceMap.getString("kazakistanLabel.toolTipText")); // NOI18N
        kazakistanLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        kazakistanLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kazakistanLabel.setName("kazakistanLabel"); // NOI18N
        mapPanel1.add(kazakistanLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 300, 90, 140));

        ucrainaLabel.setFont(resourceMap.getFont("poloniaLabel.font")); // NOI18N
        ucrainaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ucrainaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        ucrainaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        ucrainaLabel.setToolTipText(resourceMap.getString("ucrainaLabel.toolTipText")); // NOI18N
        ucrainaLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ucrainaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ucrainaLabel.setName("ucrainaLabel"); // NOI18N
        mapPanel1.add(ucrainaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, 150, 60));

        georgiaLabel.setFont(resourceMap.getFont("poloniaLabel.font")); // NOI18N
        georgiaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        georgiaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        georgiaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        georgiaLabel.setToolTipText(resourceMap.getString("georgiaLabel.toolTipText")); // NOI18N
        georgiaLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        georgiaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        georgiaLabel.setName("georgiaLabel"); // NOI18N
        mapPanel1.add(georgiaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 450, 100, 50));

        bulgariaLabel.setFont(resourceMap.getFont("poloniaLabel.font")); // NOI18N
        bulgariaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bulgariaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        bulgariaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        bulgariaLabel.setToolTipText(resourceMap.getString("bulgariaLabel.toolTipText")); // NOI18N
        bulgariaLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        bulgariaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bulgariaLabel.setName("bulgariaLabel"); // NOI18N
        mapPanel1.add(bulgariaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, 80, 40));

        romaniaLabel.setFont(resourceMap.getFont("poloniaLabel.font")); // NOI18N
        romaniaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        romaniaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        romaniaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        romaniaLabel.setToolTipText(resourceMap.getString("romaniaLabel.toolTipText")); // NOI18N
        romaniaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        romaniaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        romaniaLabel.setName("romaniaLabel"); // NOI18N
        mapPanel1.add(romaniaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 60, 60));

        greciaLabel.setFont(resourceMap.getFont("poloniaLabel.font")); // NOI18N
        greciaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        greciaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        greciaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        greciaLabel.setToolTipText(resourceMap.getString("greciaLabel.toolTipText")); // NOI18N
        greciaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        greciaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        greciaLabel.setName("greciaLabel"); // NOI18N
        mapPanel1.add(greciaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, 70, 90));

        yugoslaviaLabel.setFont(resourceMap.getFont("poloniaLabel.font")); // NOI18N
        yugoslaviaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yugoslaviaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        yugoslaviaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        yugoslaviaLabel.setToolTipText(resourceMap.getString("yugoslaviaLabel.toolTipText")); // NOI18N
        yugoslaviaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        yugoslaviaLabel.setName("yugoslaviaLabel"); // NOI18N
        mapPanel1.add(yugoslaviaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 50, 60));

        croaziaLabel.setFont(resourceMap.getFont("poloniaLabel.font")); // NOI18N
        croaziaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        croaziaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        croaziaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        croaziaLabel.setToolTipText(resourceMap.getString("croaziaLabel.toolTipText")); // NOI18N
        croaziaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        croaziaLabel.setName("croaziaLabel"); // NOI18N
        mapPanel1.add(croaziaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 50, 50));

        slovacchiaLabel.setFont(resourceMap.getFont("poloniaLabel.font")); // NOI18N
        slovacchiaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        slovacchiaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        slovacchiaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        slovacchiaLabel.setToolTipText(resourceMap.getString("slovacchiaLabel.toolTipText")); // NOI18N
        slovacchiaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        slovacchiaLabel.setName("slovacchiaLabel"); // NOI18N
        mapPanel1.add(slovacchiaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 100, 30));

        ungheriaLabel.setFont(resourceMap.getFont("poloniaLabel.font")); // NOI18N
        ungheriaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ungheriaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        ungheriaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        ungheriaLabel.setToolTipText(resourceMap.getString("ungheriaLabel.toolTipText")); // NOI18N
        ungheriaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        ungheriaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ungheriaLabel.setName("ungheriaLabel"); // NOI18N
        mapPanel1.add(ungheriaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 60, 30));

        poloniaLabel.setFont(resourceMap.getFont("poloniaLabel.font")); // NOI18N
        poloniaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        poloniaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        poloniaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        poloniaLabel.setToolTipText(resourceMap.getString("poloniaLabel.toolTipText")); // NOI18N
        poloniaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        poloniaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        poloniaLabel.setName("poloniaLabel"); // NOI18N
        mapPanel1.add(poloniaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 100, 40));

        danimarcaLabel.setFont(resourceMap.getFont("poloniaLabel.font")); // NOI18N
        danimarcaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        danimarcaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        danimarcaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        danimarcaLabel.setToolTipText(resourceMap.getString("danimarcaLabel.toolTipText")); // NOI18N
        danimarcaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        danimarcaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        danimarcaLabel.setName("danimarcaLabel"); // NOI18N
        mapPanel1.add(danimarcaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 50, 50));

        repubblicaCecaLabel.setFont(resourceMap.getFont("poloniaLabel.font")); // NOI18N
        repubblicaCecaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        repubblicaCecaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        repubblicaCecaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        repubblicaCecaLabel.setToolTipText(resourceMap.getString("repubblicaCecaLabel.toolTipText")); // NOI18N
        repubblicaCecaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        repubblicaCecaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        repubblicaCecaLabel.setName("repubblicaCecaLabel"); // NOI18N
        mapPanel1.add(repubblicaCecaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 80, 30));

        austriaLabel.setFont(resourceMap.getFont("poloniaLabel.font")); // NOI18N
        austriaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        austriaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        austriaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        austriaLabel.setToolTipText(resourceMap.getString("austriaLabel.toolTipText")); // NOI18N
        austriaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        austriaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        austriaLabel.setName("austriaLabel"); // NOI18N
        mapPanel1.add(austriaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 70, 30));

        siriaLabel.setFont(resourceMap.getFont("poloniaLabel.font")); // NOI18N
        siriaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        siriaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        siriaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        siriaLabel.setToolTipText(resourceMap.getString("siriaLabel.toolTipText")); // NOI18N
        siriaLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        siriaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        siriaLabel.setName("siriaLabel"); // NOI18N
        mapPanel1.add(siriaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 550, 80, 60));

        giordaniaLabel.setFont(resourceMap.getFont("poloniaLabel.font")); // NOI18N
        giordaniaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        giordaniaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        giordaniaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        giordaniaLabel.setToolTipText(resourceMap.getString("giordaniaLabel.toolTipText")); // NOI18N
        giordaniaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        giordaniaLabel.setName("giordaniaLabel"); // NOI18N
        mapPanel1.add(giordaniaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 620, 50, 60));

        arabiaSauditaLabel.setFont(resourceMap.getFont("poloniaLabel.font")); // NOI18N
        arabiaSauditaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        arabiaSauditaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        arabiaSauditaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        arabiaSauditaLabel.setToolTipText(resourceMap.getString("arabiaSauditaLabel.toolTipText")); // NOI18N
        arabiaSauditaLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        arabiaSauditaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        arabiaSauditaLabel.setName("arabiaSauditaLabel"); // NOI18N
        mapPanel1.add(arabiaSauditaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 640, 70, 30));

        tunisiaLabel.setFont(resourceMap.getFont("poloniaLabel.font")); // NOI18N
        tunisiaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tunisiaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        tunisiaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        tunisiaLabel.setToolTipText(resourceMap.getString("tunisiaLabel.toolTipText")); // NOI18N
        tunisiaLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        tunisiaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tunisiaLabel.setName("tunisiaLabel"); // NOI18N
        mapPanel1.add(tunisiaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 560, 60, 80));

        maroccoLabel.setFont(resourceMap.getFont("poloniaLabel.font")); // NOI18N
        maroccoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        maroccoLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        maroccoLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        maroccoLabel.setToolTipText(resourceMap.getString("maroccoLabel.toolTipText")); // NOI18N
        maroccoLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        maroccoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        maroccoLabel.setName("maroccoLabel"); // NOI18N
        mapPanel1.add(maroccoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 590, 80, 90));

        libiaLabel.setFont(resourceMap.getFont("poloniaLabel.font")); // NOI18N
        libiaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        libiaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        libiaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        libiaLabel.setToolTipText(resourceMap.getString("libiaLabel.toolTipText")); // NOI18N
        libiaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        libiaLabel.setName("libiaLabel"); // NOI18N
        mapPanel1.add(libiaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 630, 170, 50));

        algeriaLabel.setFont(resourceMap.getFont("poloniaLabel.font")); // NOI18N
        algeriaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        algeriaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        algeriaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        algeriaLabel.setToolTipText(resourceMap.getString("algeriaLabel.toolTipText")); // NOI18N
        algeriaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        algeriaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        algeriaLabel.setName("algeriaLabel"); // NOI18N
        mapPanel1.add(algeriaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 580, 120, 120));

        portogalloLabel.setFont(resourceMap.getFont("poloniaLabel.font")); // NOI18N
        portogalloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        portogalloLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        portogalloLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        portogalloLabel.setToolTipText(resourceMap.getString("portogalloLabel.toolTipText")); // NOI18N
        portogalloLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        portogalloLabel.setName("portogalloLabel"); // NOI18N
        mapPanel1.add(portogalloLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 50, 80));

        spagnaLabel.setFont(resourceMap.getFont("poloniaLabel.font")); // NOI18N
        spagnaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        spagnaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        spagnaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        spagnaLabel.setToolTipText(resourceMap.getString("spagnaLabel.toolTipText")); // NOI18N
        spagnaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        spagnaLabel.setName("spagnaLabel"); // NOI18N
        mapPanel1.add(spagnaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 100, 90));

        turchiaLabel.setFont(resourceMap.getFont("poloniaLabel.font")); // NOI18N
        turchiaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        turchiaLabel.setIcon(resourceMap.getIcon("iranLabel.icon")); // NOI18N
        turchiaLabel.setText(resourceMap.getString("iranLabel.text")); // NOI18N
        turchiaLabel.setToolTipText(resourceMap.getString("turchiaLabel.toolTipText")); // NOI18N
        turchiaLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        turchiaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        turchiaLabel.setName("turchiaLabel"); // NOI18N
        mapPanel1.add(turchiaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 480, 190, 60));

        add(mapPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    

   
       
   

   
   
  

   /* public void updateAppliance(int troops_number, int region) {

        Territorio territorio=this.tavolo.getMappa().getTerritorio(region);
        String message="Il "+territorio.getOccupante().getNome()+" posiziona "+troops_number+" in "+territorio.getNome();
        this.informationPanel.appendActionInHistory(message);
        System.out.println("ricevuto messaggio di appliance per territorio "+territorio.getNome()+" di "+troops_number+" unita");
        if(tavolo.assegnaUnita(troops_number, territorio)){
            this.territoriLabels[region].setText(Integer.toString(territorio.getNumeroUnita()));
            this.informationPanel.updateDatiGiocatore(territorio.getOccupante());
        }else{
            System.out.println("errore comunicazione appliance");
            
        }
        //showInfo("Disposizione", message);
    }*/

 /*   public void updateAttack(int troops_number, int from, int to) {
        Territorio fromTerritorio=this.tavolo.getMappa().getTerritorio(from);
        Territorio toTerritorio=this.tavolo.getMappa().getTerritorio(to);
        Giocatore  attaccante=fromTerritorio.getOccupante();
        Giocatore difensore=toTerritorio.getOccupante();
        Azione azione=tavolo.preparaAttacco(fromTerritorio, toTerritorio);
        VirtualRisikoIIEndGameBox endGameBox;
        System.out.println("ricevuto messaggio di attacco da territorio "+fromTerritorio.getNome()+"a territorio "+toTerritorio.getNome()+" con "+troops_number+" unita");
            if(azione!=null){
                azione.setNumeroTruppe(troops_number);
                tavolo.eseguiAttacco((Attacco)azione);

                this.informationPanel.appendActionInHistory(azione.toString());
                this.setLabel(azione.getDaTerritorio());
                this.setLabel(azione.getaTerritorio());
                String message="Il "+fromTerritorio.getOccupante().getNome()+" attacca da "+fromTerritorio.getNome()+"\n"+" a "+toTerritorio.getNome()+"\n"+" con "+troops_number+" unita"+
                        "attacco : ";
                if(azione.isAttacco()){

                    //variabili per i dati di Luigi
                    int [] att={0,0,0};
                    int [] dif={0,0,0};

                    int[] a=((Attacco)azione).getPunteggio();
                    String s="";
                    for(int i=0;i<a.length;i++){
                        s=s+" - "+Integer.toString(a[i]);
                        att[i]=a[i];
                    }
                    this.informationPanel.appendActionInHistory(s);
                    message=message+s+"\n"+"difesa : " ;
                    a=((Attacco)azione).getPunteggioAvversario();
                     s="";
                    for(int i=0;i<a.length;i++){
                        s=s+" - "+Integer.toString(a[i]);
                        dif[i]=a[i];
                    }
                     message=message+s;
                    this.informationPanel.appendActionInHistory(s);

                    //lancia il panel di Luigi
                    new dadiGui("Attacco da "+azione.getDaTerritorio().getNome()+" a "+azione.getaTerritorio().getNome(),att[0],att[1],att[2],dif[0],dif[1],dif[2],attaccante.getID(),difensore.getID()).setVisible(true);
                

                } 

                //azione diversa da null::controllare stato obiettivi
                if(this.tavolo.controllaObiettivoGiocatore(this.tavolo.getGiocatoreCorrente())){

                   this.showEndFrame(tavolo.getGiocatori(), tavolo.getGiocatoreCorrente());
                }

            }else{
            System.out.println("errore comunicazione attacco");
            
        }

    }*/

 /*   public void updateMovement(int troops_number, int from, int to) {
        Territorio fromTerritorio=this.tavolo.getMappa().getTerritorio(from);
        Territorio toTerritorio=this.tavolo.getMappa().getTerritorio(to);
        System.out.println("Spostamento :Il "+tavolo.getGiocatoreCorrente()+" sposta da "+fromTerritorio.getNome()+" a "+toTerritorio.getNome()+" con "+troops_number+" unita");
        Azione azione=tavolo.preparaSpostamento(fromTerritorio, toTerritorio);
        VirtualRisikoIIEndGameBox endGameBox;
        if(azione!=null){
            azione.setNumeroTruppe(troops_number);
            tavolo.eseguiSpostamento((Spostamento) azione);

                this.informationPanel.appendActionInHistory(azione.toString());
                this.setLabel(azione.getDaTerritorio());
                this.setLabel(azione.getaTerritorio());

                

                //azione diversa da null::controllare stato obiettivi
                if(this.tavolo.controllaObiettivoGiocatore(this.tavolo.getGiocatoreCorrente())){

                    this.showEndFrame(tavolo.getGiocatori(), this.tavolo.getGiocatoreCorrente());
                }

            }

    }*/

    

    

   /* public void updateChangeCards(int card1, int card2, int card3) {

        Tavolo tavolo=Tavolo.getInstance();
        Giocatore g=tavolo.getGiocatoreCorrente();
        Carta c1=g.getCarta(card1);
        Carta c2=g.getCarta(card2);
        Carta c3=g.getCarta(card3);
        int rinforzi=Rinforzo.getRinfornzo(g, c1, c2, c3, tavolo.getMappa());
        g.setNumeroTruppe(g.getNumeroTruppe()+rinforzi);
        System.out.println("Ricevuta cambio dal "+g.getNome()+" con "+c1.getTerritorio().getNome()+" "+c2.getTerritorio().getNome()+" "+c3.getTerritorio().getNome());
        this.informationPanel.updateDatiGiocatore(g);
        List<Carta> carte=tavolo.getCarte();
        carte.add(c1);
        carte.add(c2);
        carte.add(c3);

    }*/

   

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel algeriaLabel;
    private javax.swing.JLabel arabiaSauditaLabel;
    private javax.swing.JLabel austriaLabel;
    private javax.swing.JLabel bulgariaLabel;
    private javax.swing.JLabel croaziaLabel;
    private javax.swing.JLabel danimarcaLabel;
    private javax.swing.JLabel egittoLabel;
    private javax.swing.JLabel estoniaLabel;
    private javax.swing.JLabel finlandiaLabel;
    private javax.swing.JLabel franciaLabel;
    private javax.swing.JLabel georgiaLabel;
    private javax.swing.JLabel germaniaLabel;
    private javax.swing.JLabel giordaniaLabel;
    private javax.swing.JLabel greciaLabel;
    private javax.swing.JLabel iranLabel;
    private javax.swing.JLabel iraqLabel;
    private javax.swing.JLabel irlandaLabel;
    private javax.swing.JLabel islandaLabel;
    private javax.swing.JLabel italiaLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel kazakistanLabel;
    private javax.swing.JLabel libiaLabel;
    private javax.swing.JLabel lituaniaLabel;
    private virtualrisikoii.Map.europe.MapPanel mapPanel1;
    private javax.swing.JLabel maroccoLabel;
    private javax.swing.JLabel norvegiaLabel;
    private javax.swing.JLabel paesiBassiLabel;
    private javax.swing.JLabel poloniaLabel;
    private javax.swing.JLabel portogalloLabel;
    private javax.swing.JLabel regnoUnitoLabel;
    private javax.swing.JLabel repubblicaCecaLabel;
    private javax.swing.JLabel romaniaLabel;
    private javax.swing.JLabel russiaBiancaLabel;
    private javax.swing.JLabel russiaLabel;
    private javax.swing.JLabel siriaLabel;
    private javax.swing.JLabel slovacchiaLabel;
    private javax.swing.JLabel spagnaLabel;
    private javax.swing.JLabel sveziaLabel;
    private javax.swing.JLabel svizzeraLabel;
    private javax.swing.JLabel tunisiaLabel;
    private javax.swing.JLabel turchiaLabel;
    private javax.swing.JLabel ucrainaLabel;
    private javax.swing.JLabel ungheriaLabel;
    private javax.swing.JLabel yugoslaviaLabel;
    // End of variables declaration//GEN-END:variables


}
