/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJDialog.java
 *
 * Created on 12-lug-2011, 0.53.58
 */

package virtualrisikoii;

import javax.swing.JLabel;

/**
 *
 * @author root
 */
public class GameDetailsFrame extends javax.swing.JDialog {

    /** Creates new form NewJDialog */
    public GameDetailsFrame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        mapNameLabel = new javax.swing.JLabel();
        playersNumberLabel = new javax.swing.JLabel();
        maxTurnsLabel = new javax.swing.JLabel();
        maxPlayersLabel = new javax.swing.JLabel();
        peermanagerLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        tornamentLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        phaseLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Game details dialog");

        jLabel1.setText("Game name");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("map type");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText("players number");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText("max turns");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText("max players");
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText("managed by");
        jLabel6.setName("jLabel6"); // NOI18N

        nameLabel.setText("###");
        nameLabel.setName("nameLabel"); // NOI18N

        mapNameLabel.setText("###");
        mapNameLabel.setName("mapNameLabel"); // NOI18N

        playersNumberLabel.setText("###");
        playersNumberLabel.setName("playersNumberLabel"); // NOI18N

        maxTurnsLabel.setText("###");
        maxTurnsLabel.setName("maxTurnsLabel"); // NOI18N

        maxPlayersLabel.setText("###");
        maxPlayersLabel.setName("maxPlayersLabel"); // NOI18N

        peermanagerLabel.setText("###");
        peermanagerLabel.setName("peermanagerLabel"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N

        jLabel7.setText("Tournament");
        jLabel7.setName("jLabel7"); // NOI18N

        tornamentLabel.setText("###");
        tornamentLabel.setName("tornamentLabel"); // NOI18N

        jLabel8.setText("Phase");
        jLabel8.setName("jLabel8"); // NOI18N

        phaseLabel.setText("###");
        phaseLabel.setName("phaseLabel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(mapNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(playersNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(maxTurnsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(maxPlayersLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(peermanagerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(61, 61, 61)
                        .addComponent(tornamentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(90, 90, 90)
                        .addComponent(phaseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mapNameLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(playersNumberLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(maxTurnsLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(maxPlayersLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(peermanagerLabel))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tornamentLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(phaseLabel))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getMapNameLabel() {
        return mapNameLabel;
    }

    public JLabel getMaxPlayersLabel() {
        return maxPlayersLabel;
    }

    public JLabel getMaxTurnsLabel() {
        return maxTurnsLabel;
    }

    public JLabel getNameLabel() {
        return nameLabel;
    }

    public JLabel getPeermanagerLabel() {
        return peermanagerLabel;
    }

    public JLabel getPhaseLabel() {
        return phaseLabel;
    }

    public JLabel getPlayersNumberLabel() {
        return playersNumberLabel;
    }

    public JLabel getTornamentLabel() {
        return tornamentLabel;
    }

    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GameDetailsFrame dialog = new GameDetailsFrame(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mapNameLabel;
    private javax.swing.JLabel maxPlayersLabel;
    private javax.swing.JLabel maxTurnsLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel peermanagerLabel;
    private javax.swing.JLabel phaseLabel;
    private javax.swing.JLabel playersNumberLabel;
    private javax.swing.JLabel tornamentLabel;
    // End of variables declaration//GEN-END:variables

}
