/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InformationPanel.java
 *
 * Created on 30-apr-2011, 12.31.39
 */

package virtualrisikoii;

import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.border.TitledBorder;
import jxta.communication.Communicator;
import net.jxta.endpoint.Message;
import virtualrisikoii.listener.ChatListener;
import virtualrisikoii.listener.PassListener;
import virtualrisikoii.risiko.Giocatore;
import virtualrisikoii.risiko.Tavolo;
import virtualrisikoii.risiko.Territorio;

/**
 *
 * @author root
 */
public class InformationPanel extends javax.swing.JPanel implements ChatListener,PassListener{

    private Tavolo tavolo;
    private Communicator communicator;

    /** Creates new form InformationPanel */
    public InformationPanel() {
        initComponents();
        communicator=Communicator.getInstance();
        communicator.addChatListener(this);
        communicator.addPassListener(this);
        tavolo=Tavolo.getInstance();
        int idObiettivo=tavolo.getMyGiocatore().getObiettivo().getCodice()+1;
        obiettivoLabel.setIcon(new ImageIcon("src/virtualrisikoii/resources/obiettivi/classical/"+idObiettivo+".jpg"));
       System.out.println("/src/virtualrisikoii/resources/obiettivi/classical/"+tavolo.getMyGiocatore().getObiettivo().getCodice()+".jpg");
        this.obiettivoLabel.setToolTipText(tavolo.getMyGiocatore().getObiettivo().toString());
        TitledBorder border= (TitledBorder) this.getBorder();
        border.setTitle("Benvenuto "+tavolo.getMyGiocatore().getNome());
        border= (TitledBorder) this.jPanel1.getBorder();
        border.setTitle("Informazioni obiettivo "+tavolo.getMyGiocatore().getNome());

    }

    public void setTavolo(Tavolo tavolo){
        this.tavolo=tavolo;
    }


    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        obiettivoLabel = new javax.swing.JLabel();
        passaTurnoButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        chatTextArea = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gameInformationArea = new javax.swing.JTextArea();
        turnoPanel = new javax.swing.JPanel();
        turnoLabel = new javax.swing.JLabel();
        truppeLabel = new javax.swing.JLabel();
        arnatedisposteLabel = new javax.swing.JLabel();
        terrLabel = new javax.swing.JLabel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(InformationPanel.class);
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("Form.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("Form.border.titleFont"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(255, 727));
        setMinimumSize(new java.awt.Dimension(255, 727));
        setName("Form"); // NOI18N

        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel1.border.title"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        obiettivoLabel.setIcon(resourceMap.getIcon("obiettivoLabel.icon")); // NOI18N
        obiettivoLabel.setText(resourceMap.getString("obiettivoLabel.text")); // NOI18N
        obiettivoLabel.setName("obiettivoLabel"); // NOI18N

        passaTurnoButton.setText(resourceMap.getString("passaTurnoButton.text")); // NOI18N
        passaTurnoButton.setName("passaTurnoButton"); // NOI18N
        passaTurnoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passaTurnoButtonActionPerformed(evt);
            }
        });

        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(obiettivoLabel)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(passaTurnoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(obiettivoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passaTurnoButton)
                    .addComponent(jButton3)))
        );

        jPanel4.setBackground(resourceMap.getColor("jPanel4.background")); // NOI18N
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel4.border.title"))); // NOI18N
        jPanel4.setName("jPanel4"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        chatTextArea.setColumns(20);
        chatTextArea.setEditable(false);
        chatTextArea.setFont(resourceMap.getFont("chatTextArea.font")); // NOI18N
        chatTextArea.setRows(5);
        chatTextArea.setName("chatTextArea"); // NOI18N
        jScrollPane2.setViewportView(chatTextArea);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
        );

        jPanel2.setBackground(resourceMap.getColor("jPanel2.background")); // NOI18N
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel2.border.title"))); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setName("jScrollPane1"); // NOI18N

        gameInformationArea.setColumns(20);
        gameInformationArea.setEditable(false);
        gameInformationArea.setFont(resourceMap.getFont("gameInformationArea.font")); // NOI18N
        gameInformationArea.setRows(5);
        gameInformationArea.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        gameInformationArea.setDropMode(javax.swing.DropMode.INSERT);
        gameInformationArea.setName("gameInformationArea"); // NOI18N
        jScrollPane1.setViewportView(gameInformationArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addContainerGap())
        );

        turnoPanel.setBackground(resourceMap.getColor("turnoPanel.background")); // NOI18N
        turnoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("turnoPanel.border.title"))); // NOI18N
        turnoPanel.setName("turnoPanel"); // NOI18N

        turnoLabel.setText(resourceMap.getString("turnoLabel.text")); // NOI18N
        turnoLabel.setName("turnoLabel"); // NOI18N

        truppeLabel.setText(resourceMap.getString("truppeLabel.text")); // NOI18N
        truppeLabel.setName("truppeLabel"); // NOI18N

        arnatedisposteLabel.setText(resourceMap.getString("arnatedisposteLabel.text")); // NOI18N
        arnatedisposteLabel.setName("arnatedisposteLabel"); // NOI18N

        terrLabel.setText(resourceMap.getString("terrLabel.text")); // NOI18N
        terrLabel.setName("terrLabel"); // NOI18N

        javax.swing.GroupLayout turnoPanelLayout = new javax.swing.GroupLayout(turnoPanel);
        turnoPanel.setLayout(turnoPanelLayout);
        turnoPanelLayout.setHorizontalGroup(
            turnoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(turnoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
            .addGroup(turnoPanelLayout.createSequentialGroup()
                .addComponent(truppeLabel)
                .addGap(39, 39, 39)
                .addComponent(arnatedisposteLabel)
                .addGap(53, 53, 53)
                .addComponent(terrLabel)
                .addContainerGap())
        );
        turnoPanelLayout.setVerticalGroup(
            turnoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(turnoPanelLayout.createSequentialGroup()
                .addComponent(turnoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(turnoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(truppeLabel)
                    .addComponent(terrLabel)
                    .addComponent(arnatedisposteLabel))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(turnoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(turnoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void passaTurnoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passaTurnoButtonActionPerformed
        // TODO add your handling code here:
        if((!tavolo.isInizializzazione())&&tavolo.isTurnoMyGiocatore()){
            this.tavolo.passaTurno();
            Message msg=this.communicator.createPassesMessage(tavolo.getTurnoSuccessivo());
            try {
                        //Thread.sleep(3000);
                        this.communicator.sendMessage(msg);
                       

                    } catch (Exception  ex) {
                        ex.printStackTrace();
                    } 
            this.updateDatiGiocatore(tavolo.getGiocatoreCorrente());
        }
        
    }//GEN-LAST:event_passaTurnoButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(!tavolo.isInizializzazione()){
            if(this.tavolo.recuperaCarta(tavolo.getGiocatoreCorrente()))
                this.updateDatiGiocatore(this.tavolo.getGiocatoreCorrente());
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed


    public void updateDatiGiocatore(Giocatore giocatore){
        this.turnoLabel.setText("Turno : "+giocatore.getNome());
        this.truppeLabel.setText("truppe : "+giocatore.getNumeroTruppe());
        this.arnatedisposteLabel.setText("armate : "+giocatore.getArmateDisposte());
        this.terrLabel.setText("terr : "+giocatore.getNazioni().size());



        this.repaint();
    }



    public void appendActionInHistory(String action){
        this.gameInformationArea.append("\n"+action);
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arnatedisposteLabel;
    private javax.swing.JTextArea chatTextArea;
    private javax.swing.JTextArea gameInformationArea;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel obiettivoLabel;
    private javax.swing.JButton passaTurnoButton;
    private javax.swing.JLabel terrLabel;
    private javax.swing.JLabel truppeLabel;
    private javax.swing.JLabel turnoLabel;
    private javax.swing.JPanel turnoPanel;
    // End of variables declaration//GEN-END:variables

    public void updateChat(String to, String messageString) {
        if(to.equals(Communicator.ChatAttributes.TO_ALL)||to.equals(Tavolo.getInstance().getMyGiocatore().getNome()))
        this.chatTextArea.append(messageString);
    }

    public void updatePass(int turno_successivo) {


            int turnoSucc=tavolo.getTurnoSuccessivo();
            if(turnoSucc==0&&tavolo.getGiocatori().get(0).getNumeroTruppe()==0){
                tavolo.setInizializzazione(false);
            }

            this.tavolo.passaTurno();
            
            
            this.updateDatiGiocatore(tavolo.getGiocatoreCorrente());
            if(tavolo.isTurnoMyGiocatore()){

                this.appendActionInHistory(tavolo.getGiocatoreCorrente().getNome()+" ancora "+tavolo.getGiocatoreCorrente().getNumeroTruppe());
                System.out.println("ancora in inizializzazione "+tavolo.isInizializzazione());
            }
        

    }

    
}
