/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ItaliaMapPanel.java
 *
 * Created on 20-apr-2011, 22.08.01
 */

package virtualrisikoii.Map.italia;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Iterator;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import services.CardListener;
import services.GameController;
import services.MapListener;
import services.TroopsSelector;
import services.VictoryListener;
import virtualrisikoii.ActionDialog;
import virtualrisikoii.EndGameFrame;
import virtualrisikoii.XMapPanel;
import virtualrisikoii.risiko.Giocatore;
import virtualrisikoii.risiko.JFrameCarte;
import virtualrisikoii.risiko.JFrameDadi;
import virtualrisikoii.risiko.dadiGui;

/**
 *
 * @author root
 */
public class ItaliaMapPanel extends XMapPanel {

    


    /** Creates new form ItaliaMapPanel */
    public ItaliaMapPanel() {
        gameController=GameController.getInstance();
        gameController.setMapListener(this);
        gameController.setTroopsSelector(this);
        gameController.setVictoryListener(this);
        gameController.setCardListener(this);
        initComponents();
        territoriLabels=new JLabel[42];
        territoriLabels[0]=aostaaLabel;
        territoriLabels[1]=torinoLabel;
        territoriLabels[2]=alessandriaLabel;
        territoriLabels[3]=cuneoLabel;
        territoriLabels[4]=imperiaLabel;
        territoriLabels[5]=genovaLabel;
        territoriLabels[6]=parmaLabel;
        territoriLabels[7]=milanoLabel;
        territoriLabels[8]=bergamoLabel;
        territoriLabels[9]=bresciaLabel;
        territoriLabels[10]=trentoLabel;
        territoriLabels[11]=veronaLabel;
        territoriLabels[12]=veneziaLabel;
        territoriLabels[13]=triesteLabel;
        territoriLabels[14]=bolognaLabel;
        territoriLabels[15]=riminiLabel;
        territoriLabels[16]=firenzeLabel;
        territoriLabels[17]=pisaLabel;
        territoriLabels[18]=sienaLabel;
        territoriLabels[19]=perugiaLabel;
        territoriLabels[20]=pesaroLabel;
        territoriLabels[21]=anconaLabel;
        territoriLabels[22]=viterboLabel;
        territoriLabels[23]=romaLabel;
        territoriLabels[24]=lAquilaLabel;
        territoriLabels[25]=latinaLabel;
        territoriLabels[26]=campobassoLabel;
        territoriLabels[27]=napoliLabel;
        territoriLabels[28]=foggiaLabel;
        territoriLabels[29]=salernoLabel;
        territoriLabels[30]=potenzaLabel;
        territoriLabels[31]=bariLabel;
        territoriLabels[32]=lecceLabel;
        territoriLabels[33]=catanzaroLabel;
        territoriLabels[34]=reggioCalabriaLabel;
        territoriLabels[35]=messinaLabel;
        territoriLabels[36]=agrigentoLabel;
        territoriLabels[37]=palermoLabel;
        territoriLabels[38]=trapaniLabel;
        territoriLabels[39]=cagliariLabel;
        territoriLabels[40]=nuoroLabel;
        territoriLabels[41]=sassariLabel;

        LabelSelector selector=new LabelSelector();
        for(int i=0;i<territoriLabels.length;i++){
            this.territoriLabels[i].addMouseListener(selector);
        }

        initIconPlayers();
        gameController.initMap();


        
    }

   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        mapPanel1 = new virtualrisikoii.Map.italia.MapPanel();
        bolognaLabel = new javax.swing.JLabel();
        perugiaLabel = new javax.swing.JLabel();
        riminiLabel = new javax.swing.JLabel();
        campobassoLabel = new javax.swing.JLabel();
        napoliLabel = new javax.swing.JLabel();
        foggiaLabel = new javax.swing.JLabel();
        potenzaLabel = new javax.swing.JLabel();
        aostaaLabel = new javax.swing.JLabel();
        imperiaLabel = new javax.swing.JLabel();
        salernoLabel = new javax.swing.JLabel();
        torinoLabel = new javax.swing.JLabel();
        cuneoLabel = new javax.swing.JLabel();
        parmaLabel = new javax.swing.JLabel();
        genovaLabel = new javax.swing.JLabel();
        alessandriaLabel = new javax.swing.JLabel();
        milanoLabel = new javax.swing.JLabel();
        bergamoLabel = new javax.swing.JLabel();
        bresciaLabel = new javax.swing.JLabel();
        veronaLabel = new javax.swing.JLabel();
        trentoLabel = new javax.swing.JLabel();
        veneziaLabel = new javax.swing.JLabel();
        nuoroLabel = new javax.swing.JLabel();
        sassariLabel = new javax.swing.JLabel();
        cagliariLabel = new javax.swing.JLabel();
        trapaniLabel = new javax.swing.JLabel();
        palermoLabel = new javax.swing.JLabel();
        messinaLabel = new javax.swing.JLabel();
        agrigentoLabel = new javax.swing.JLabel();
        lecceLabel = new javax.swing.JLabel();
        bariLabel = new javax.swing.JLabel();
        catanzaroLabel = new javax.swing.JLabel();
        reggioCalabriaLabel = new javax.swing.JLabel();
        firenzeLabel = new javax.swing.JLabel();
        sienaLabel = new javax.swing.JLabel();
        pisaLabel = new javax.swing.JLabel();
        anconaLabel = new javax.swing.JLabel();
        romaLabel = new javax.swing.JLabel();
        pesaroLabel = new javax.swing.JLabel();
        viterboLabel = new javax.swing.JLabel();
        lAquilaLabel = new javax.swing.JLabel();
        latinaLabel = new javax.swing.JLabel();
        triesteLabel = new javax.swing.JLabel();

        jLabel2.setName("jLabel2"); // NOI18N

        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.BorderLayout());

        mapPanel1.setName("mapPanel1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(ItaliaMapPanel.class);
        bolognaLabel.setFont(resourceMap.getFont("bolognaLabel.font")); // NOI18N
        bolognaLabel.setForeground(resourceMap.getColor("bolognaLabel.foreground")); // NOI18N
        bolognaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bolognaLabel.setText(resourceMap.getString("bolognaLabel.text")); // NOI18N
        bolognaLabel.setToolTipText(resourceMap.getString("bolognaLabel.toolTipText")); // NOI18N
        bolognaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bolognaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bolognaLabel.setName("bolognaLabel"); // NOI18N
        mapPanel1.add(bolognaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 50, 50));

        perugiaLabel.setFont(resourceMap.getFont("bolognaLabel.font")); // NOI18N
        perugiaLabel.setForeground(resourceMap.getColor("bolognaLabel.foreground")); // NOI18N
        perugiaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        perugiaLabel.setText(resourceMap.getString("perugiaLabel.text")); // NOI18N
        perugiaLabel.setToolTipText(resourceMap.getString("perugiaLabel.toolTipText")); // NOI18N
        perugiaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        perugiaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        perugiaLabel.setName("perugiaLabel"); // NOI18N
        mapPanel1.add(perugiaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 60, 40));

        riminiLabel.setFont(resourceMap.getFont("bolognaLabel.font")); // NOI18N
        riminiLabel.setForeground(resourceMap.getColor("bolognaLabel.foreground")); // NOI18N
        riminiLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        riminiLabel.setText(resourceMap.getString("riminiLabel.text")); // NOI18N
        riminiLabel.setToolTipText(resourceMap.getString("riminiLabel.toolTipText")); // NOI18N
        riminiLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        riminiLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        riminiLabel.setName("riminiLabel"); // NOI18N
        mapPanel1.add(riminiLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 140, 40));

        campobassoLabel.setFont(resourceMap.getFont("bolognaLabel.font")); // NOI18N
        campobassoLabel.setForeground(resourceMap.getColor("bolognaLabel.foreground")); // NOI18N
        campobassoLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        campobassoLabel.setText(resourceMap.getString("campobassoLabel.text")); // NOI18N
        campobassoLabel.setToolTipText(resourceMap.getString("campobassoLabel.toolTipText")); // NOI18N
        campobassoLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        campobassoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        campobassoLabel.setName("campobassoLabel"); // NOI18N
        mapPanel1.add(campobassoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 70, 20));

        napoliLabel.setFont(resourceMap.getFont("bolognaLabel.font")); // NOI18N
        napoliLabel.setForeground(resourceMap.getColor("bolognaLabel.foreground")); // NOI18N
        napoliLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        napoliLabel.setText(resourceMap.getString("napoliLabel.text")); // NOI18N
        napoliLabel.setToolTipText(resourceMap.getString("napoliLabel.toolTipText")); // NOI18N
        napoliLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        napoliLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        napoliLabel.setName("napoliLabel"); // NOI18N
        mapPanel1.add(napoliLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, 70, 70));

        foggiaLabel.setFont(resourceMap.getFont("bolognaLabel.font")); // NOI18N
        foggiaLabel.setForeground(resourceMap.getColor("bolognaLabel.foreground")); // NOI18N
        foggiaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        foggiaLabel.setText(resourceMap.getString("foggiaLabel.text")); // NOI18N
        foggiaLabel.setToolTipText(resourceMap.getString("foggiaLabel.toolTipText")); // NOI18N
        foggiaLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        foggiaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        foggiaLabel.setName("foggiaLabel"); // NOI18N
        mapPanel1.add(foggiaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 330, 150, 30));

        potenzaLabel.setFont(resourceMap.getFont("bolognaLabel.font")); // NOI18N
        potenzaLabel.setForeground(resourceMap.getColor("bolognaLabel.foreground")); // NOI18N
        potenzaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        potenzaLabel.setText(resourceMap.getString("potenzaLabel.text")); // NOI18N
        potenzaLabel.setToolTipText(resourceMap.getString("potenzaLabel.toolTipText")); // NOI18N
        potenzaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        potenzaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        potenzaLabel.setName("potenzaLabel"); // NOI18N
        mapPanel1.add(potenzaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, 60, 40));

        aostaaLabel.setFont(resourceMap.getFont("bolognaLabel.font")); // NOI18N
        aostaaLabel.setForeground(resourceMap.getColor("bolognaLabel.foreground")); // NOI18N
        aostaaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        aostaaLabel.setText(resourceMap.getString("aostaaLabel.text")); // NOI18N
        aostaaLabel.setToolTipText(resourceMap.getString("aostaaLabel.toolTipText")); // NOI18N
        aostaaLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        aostaaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aostaaLabel.setName("aostaaLabel"); // NOI18N
        mapPanel1.add(aostaaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 130, 50));

        imperiaLabel.setFont(resourceMap.getFont("bolognaLabel.font")); // NOI18N
        imperiaLabel.setForeground(resourceMap.getColor("bolognaLabel.foreground")); // NOI18N
        imperiaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        imperiaLabel.setText(resourceMap.getString("imperiaLabel.text")); // NOI18N
        imperiaLabel.setToolTipText(resourceMap.getString("imperiaLabel.toolTipText")); // NOI18N
        imperiaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        imperiaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imperiaLabel.setName("imperiaLabel"); // NOI18N
        mapPanel1.add(imperiaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 150, 70));

        salernoLabel.setFont(resourceMap.getFont("bolognaLabel.font")); // NOI18N
        salernoLabel.setForeground(resourceMap.getColor("bolognaLabel.foreground")); // NOI18N
        salernoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        salernoLabel.setText(resourceMap.getString("salernoLabel.text")); // NOI18N
        salernoLabel.setToolTipText(resourceMap.getString("salernoLabel.toolTipText")); // NOI18N
        salernoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salernoLabel.setName("salernoLabel"); // NOI18N
        mapPanel1.add(salernoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, 60, 70));

        torinoLabel.setFont(resourceMap.getFont("bolognaLabel.font")); // NOI18N
        torinoLabel.setForeground(resourceMap.getColor("bolognaLabel.foreground")); // NOI18N
        torinoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        torinoLabel.setText(resourceMap.getString("torinoLabel.text")); // NOI18N
        torinoLabel.setToolTipText(resourceMap.getString("torinoLabel.toolTipText")); // NOI18N
        torinoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        torinoLabel.setName("torinoLabel"); // NOI18N
        mapPanel1.add(torinoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 140, 60));

        cuneoLabel.setFont(resourceMap.getFont("bolognaLabel.font")); // NOI18N
        cuneoLabel.setForeground(resourceMap.getColor("bolognaLabel.foreground")); // NOI18N
        cuneoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cuneoLabel.setText(resourceMap.getString("cuneoLabel.text")); // NOI18N
        cuneoLabel.setToolTipText(resourceMap.getString("cuneoLabel.toolTipText")); // NOI18N
        cuneoLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        cuneoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cuneoLabel.setName("cuneoLabel"); // NOI18N
        mapPanel1.add(cuneoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 110, 30));

        parmaLabel.setFont(resourceMap.getFont("bolognaLabel.font")); // NOI18N
        parmaLabel.setForeground(resourceMap.getColor("bolognaLabel.foreground")); // NOI18N
        parmaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        parmaLabel.setText(resourceMap.getString("parmaLabel.text")); // NOI18N
        parmaLabel.setToolTipText(resourceMap.getString("parmaLabel.toolTipText")); // NOI18N
        parmaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        parmaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        parmaLabel.setName("parmaLabel"); // NOI18N
        mapPanel1.add(parmaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 70, 40));

        genovaLabel.setFont(resourceMap.getFont("bolognaLabel.font")); // NOI18N
        genovaLabel.setForeground(resourceMap.getColor("bolognaLabel.foreground")); // NOI18N
        genovaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        genovaLabel.setText(resourceMap.getString("genovaLabel.text")); // NOI18N
        genovaLabel.setToolTipText(resourceMap.getString("genovaLabel.toolTipText")); // NOI18N
        genovaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        genovaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        genovaLabel.setName("genovaLabel"); // NOI18N
        mapPanel1.add(genovaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 70, 70));

        alessandriaLabel.setFont(resourceMap.getFont("bolognaLabel.font")); // NOI18N
        alessandriaLabel.setForeground(resourceMap.getColor("bolognaLabel.foreground")); // NOI18N
        alessandriaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alessandriaLabel.setText(resourceMap.getString("alessandriaLabel.text")); // NOI18N
        alessandriaLabel.setToolTipText(resourceMap.getString("alessandriaLabel.toolTipText")); // NOI18N
        alessandriaLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        alessandriaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        alessandriaLabel.setName("alessandriaLabel"); // NOI18N
        mapPanel1.add(alessandriaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 60, 100));

        milanoLabel.setFont(resourceMap.getFont("bolognaLabel.font")); // NOI18N
        milanoLabel.setForeground(resourceMap.getColor("bolognaLabel.foreground")); // NOI18N
        milanoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        milanoLabel.setText(resourceMap.getString("milanoLabel.text")); // NOI18N
        milanoLabel.setToolTipText(resourceMap.getString("milanoLabel.toolTipText")); // NOI18N
        milanoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        milanoLabel.setName("milanoLabel"); // NOI18N
        mapPanel1.add(milanoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 80, 30));

        bergamoLabel.setFont(resourceMap.getFont("bolognaLabel.font")); // NOI18N
        bergamoLabel.setForeground(resourceMap.getColor("bolognaLabel.foreground")); // NOI18N
        bergamoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bergamoLabel.setText(resourceMap.getString("bergamoLabel.text")); // NOI18N
        bergamoLabel.setToolTipText(resourceMap.getString("bergamoLabel.toolTipText")); // NOI18N
        bergamoLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        bergamoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bergamoLabel.setName("bergamoLabel"); // NOI18N
        mapPanel1.add(bergamoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 60, 80));

        bresciaLabel.setFont(resourceMap.getFont("bolognaLabel.font")); // NOI18N
        bresciaLabel.setForeground(resourceMap.getColor("bolognaLabel.foreground")); // NOI18N
        bresciaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bresciaLabel.setText(resourceMap.getString("bresciaLabel.text")); // NOI18N
        bresciaLabel.setToolTipText(resourceMap.getString("bresciaLabel.toolTipText")); // NOI18N
        bresciaLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        bresciaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bresciaLabel.setName("bresciaLabel"); // NOI18N
        mapPanel1.add(bresciaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 60, 60));

        veronaLabel.setFont(resourceMap.getFont("bolognaLabel.font")); // NOI18N
        veronaLabel.setForeground(resourceMap.getColor("bolognaLabel.foreground")); // NOI18N
        veronaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        veronaLabel.setText(resourceMap.getString("veronaLabel.text")); // NOI18N
        veronaLabel.setToolTipText(resourceMap.getString("veronaLabel.toolTipText")); // NOI18N
        veronaLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        veronaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        veronaLabel.setName("veronaLabel"); // NOI18N
        mapPanel1.add(veronaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 80, 40));

        trentoLabel.setFont(resourceMap.getFont("bolognaLabel.font")); // NOI18N
        trentoLabel.setForeground(resourceMap.getColor("bolognaLabel.foreground")); // NOI18N
        trentoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        trentoLabel.setText(resourceMap.getString("trentoLabel.text")); // NOI18N
        trentoLabel.setToolTipText(resourceMap.getString("trentoLabel.toolTipText")); // NOI18N
        trentoLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        trentoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        trentoLabel.setName("trentoLabel"); // NOI18N
        mapPanel1.add(trentoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 90, 90));

        veneziaLabel.setFont(resourceMap.getFont("bolognaLabel.font")); // NOI18N
        veneziaLabel.setForeground(resourceMap.getColor("bolognaLabel.foreground")); // NOI18N
        veneziaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        veneziaLabel.setText(resourceMap.getString("veneziaLabel.text")); // NOI18N
        veneziaLabel.setToolTipText(resourceMap.getString("veneziaLabel.toolTipText")); // NOI18N
        veneziaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        veneziaLabel.setName("veneziaLabel"); // NOI18N
        mapPanel1.add(veneziaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 50, 110));

        nuoroLabel.setFont(resourceMap.getFont("bolognaLabel.font")); // NOI18N
        nuoroLabel.setForeground(resourceMap.getColor("bolognaLabel.foreground")); // NOI18N
        nuoroLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nuoroLabel.setText(resourceMap.getString("nuoroLabel.text")); // NOI18N
        nuoroLabel.setToolTipText(resourceMap.getString("nuoroLabel.toolTipText")); // NOI18N
        nuoroLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        nuoroLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nuoroLabel.setName("nuoroLabel"); // NOI18N
        mapPanel1.add(nuoroLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 120, 80));

        sassariLabel.setFont(resourceMap.getFont("bolognaLabel.font")); // NOI18N
        sassariLabel.setForeground(resourceMap.getColor("bolognaLabel.foreground")); // NOI18N
        sassariLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        sassariLabel.setText(resourceMap.getString("sassariLabel.text")); // NOI18N
        sassariLabel.setToolTipText(resourceMap.getString("sassariLabel.toolTipText")); // NOI18N
        sassariLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sassariLabel.setName("sassariLabel"); // NOI18N
        mapPanel1.add(sassariLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 110, 80));

        cagliariLabel.setFont(resourceMap.getFont("bolognaLabel.font")); // NOI18N
        cagliariLabel.setForeground(resourceMap.getColor("bolognaLabel.foreground")); // NOI18N
        cagliariLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cagliariLabel.setText(resourceMap.getString("cagliariLabel.text")); // NOI18N
        cagliariLabel.setToolTipText(resourceMap.getString("cagliariLabel.toolTipText")); // NOI18N
        cagliariLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        cagliariLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cagliariLabel.setName("cagliariLabel"); // NOI18N
        mapPanel1.add(cagliariLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 70, 110));

        trapaniLabel.setFont(resourceMap.getFont("bolognaLabel.font")); // NOI18N
        trapaniLabel.setForeground(resourceMap.getColor("bolognaLabel.foreground")); // NOI18N
        trapaniLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        trapaniLabel.setText(resourceMap.getString("trapaniLabel.text")); // NOI18N
        trapaniLabel.setToolTipText(resourceMap.getString("trapaniLabel.toolTipText")); // NOI18N
        trapaniLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        trapaniLabel.setName("trapaniLabel"); // NOI18N
        mapPanel1.add(trapaniLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, 130, 90));

        palermoLabel.setFont(resourceMap.getFont("bolognaLabel.font")); // NOI18N
        palermoLabel.setForeground(resourceMap.getColor("bolognaLabel.foreground")); // NOI18N
        palermoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        palermoLabel.setText(resourceMap.getString("palermoLabel.text")); // NOI18N
        palermoLabel.setToolTipText(resourceMap.getString("palermoLabel.toolTipText")); // NOI18N
        palermoLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        palermoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        palermoLabel.setName("palermoLabel"); // NOI18N
        mapPanel1.add(palermoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 500, 70, 70));

        messinaLabel.setFont(resourceMap.getFont("bolognaLabel.font")); // NOI18N
        messinaLabel.setForeground(resourceMap.getColor("bolognaLabel.foreground")); // NOI18N
        messinaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        messinaLabel.setText(resourceMap.getString("messinaLabel.text")); // NOI18N
        messinaLabel.setToolTipText(resourceMap.getString("messinaLabel.toolTipText")); // NOI18N
        messinaLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        messinaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        messinaLabel.setName("messinaLabel"); // NOI18N
        mapPanel1.add(messinaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 540, 80, 40));

        agrigentoLabel.setFont(resourceMap.getFont("bolognaLabel.font")); // NOI18N
        agrigentoLabel.setForeground(resourceMap.getColor("bolognaLabel.foreground")); // NOI18N
        agrigentoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agrigentoLabel.setText(resourceMap.getString("agrigentoLabel.text")); // NOI18N
        agrigentoLabel.setToolTipText(resourceMap.getString("agrigentoLabel.toolTipText")); // NOI18N
        agrigentoLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        agrigentoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agrigentoLabel.setName("agrigentoLabel"); // NOI18N
        mapPanel1.add(agrigentoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 590, 140, 50));

        lecceLabel.setFont(resourceMap.getFont("bolognaLabel.font")); // NOI18N
        lecceLabel.setForeground(resourceMap.getColor("bolognaLabel.foreground")); // NOI18N
        lecceLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lecceLabel.setText(resourceMap.getString("lecceLabel.text")); // NOI18N
        lecceLabel.setToolTipText(resourceMap.getString("lecceLabel.toolTipText")); // NOI18N
        lecceLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lecceLabel.setName("lecceLabel"); // NOI18N
        mapPanel1.add(lecceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 370, 90, 90));

        bariLabel.setFont(resourceMap.getFont("bolognaLabel.font")); // NOI18N
        bariLabel.setForeground(resourceMap.getColor("bolognaLabel.foreground")); // NOI18N
        bariLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bariLabel.setText(resourceMap.getString("bariLabel.text")); // NOI18N
        bariLabel.setToolTipText(resourceMap.getString("bariLabel.toolTipText")); // NOI18N
        bariLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        bariLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bariLabel.setName("bariLabel"); // NOI18N
        mapPanel1.add(bariLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 360, 110, 30));

        catanzaroLabel.setFont(resourceMap.getFont("bolognaLabel.font")); // NOI18N
        catanzaroLabel.setForeground(resourceMap.getColor("bolognaLabel.foreground")); // NOI18N
        catanzaroLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        catanzaroLabel.setText(resourceMap.getString("catanzaroLabel.text")); // NOI18N
        catanzaroLabel.setToolTipText(resourceMap.getString("catanzaroLabel.toolTipText")); // NOI18N
        catanzaroLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        catanzaroLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        catanzaroLabel.setName("catanzaroLabel"); // NOI18N
        mapPanel1.add(catanzaroLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 450, 100, 40));

        reggioCalabriaLabel.setFont(resourceMap.getFont("bolognaLabel.font")); // NOI18N
        reggioCalabriaLabel.setForeground(resourceMap.getColor("bolognaLabel.foreground")); // NOI18N
        reggioCalabriaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        reggioCalabriaLabel.setText(resourceMap.getString("reggioCalabriaLabel.text")); // NOI18N
        reggioCalabriaLabel.setToolTipText(resourceMap.getString("reggioCalabriaLabel.toolTipText")); // NOI18N
        reggioCalabriaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        reggioCalabriaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reggioCalabriaLabel.setName("reggioCalabriaLabel"); // NOI18N
        mapPanel1.add(reggioCalabriaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 510, 70, 80));

        firenzeLabel.setFont(resourceMap.getFont("bolognaLabel.font")); // NOI18N
        firenzeLabel.setForeground(resourceMap.getColor("bolognaLabel.foreground")); // NOI18N
        firenzeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        firenzeLabel.setText(resourceMap.getString("firenzeLabel.text")); // NOI18N
        firenzeLabel.setToolTipText(resourceMap.getString("firenzeLabel.toolTipText")); // NOI18N
        firenzeLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        firenzeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        firenzeLabel.setName("firenzeLabel"); // NOI18N
        mapPanel1.add(firenzeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 80, 30));

        sienaLabel.setFont(resourceMap.getFont("bolognaLabel.font")); // NOI18N
        sienaLabel.setForeground(resourceMap.getColor("bolognaLabel.foreground")); // NOI18N
        sienaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        sienaLabel.setText(resourceMap.getString("sienaLabel.text")); // NOI18N
        sienaLabel.setToolTipText(resourceMap.getString("sienaLabel.toolTipText")); // NOI18N
        sienaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sienaLabel.setName("sienaLabel"); // NOI18N
        mapPanel1.add(sienaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 90, 40));

        pisaLabel.setFont(resourceMap.getFont("bolognaLabel.font")); // NOI18N
        pisaLabel.setForeground(resourceMap.getColor("bolognaLabel.foreground")); // NOI18N
        pisaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pisaLabel.setText(resourceMap.getString("pisaLabel.text")); // NOI18N
        pisaLabel.setToolTipText(resourceMap.getString("pisaLabel.toolTipText")); // NOI18N
        pisaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pisaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pisaLabel.setName("pisaLabel"); // NOI18N
        mapPanel1.add(pisaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 50, 50));

        anconaLabel.setFont(resourceMap.getFont("bolognaLabel.font")); // NOI18N
        anconaLabel.setForeground(resourceMap.getColor("bolognaLabel.foreground")); // NOI18N
        anconaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        anconaLabel.setText(resourceMap.getString("anconaLabel.text")); // NOI18N
        anconaLabel.setToolTipText(resourceMap.getString("anconaLabel.toolTipText")); // NOI18N
        anconaLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        anconaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        anconaLabel.setName("anconaLabel"); // NOI18N
        mapPanel1.add(anconaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 160, 20));

        romaLabel.setFont(resourceMap.getFont("bolognaLabel.font")); // NOI18N
        romaLabel.setForeground(resourceMap.getColor("bolognaLabel.foreground")); // NOI18N
        romaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        romaLabel.setText(resourceMap.getString("romaLabel.text")); // NOI18N
        romaLabel.setToolTipText(resourceMap.getString("romaLabel.toolTipText")); // NOI18N
        romaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        romaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        romaLabel.setName("romaLabel"); // NOI18N
        mapPanel1.add(romaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 50, 40));

        pesaroLabel.setFont(resourceMap.getFont("bolognaLabel.font")); // NOI18N
        pesaroLabel.setForeground(resourceMap.getColor("bolognaLabel.foreground")); // NOI18N
        pesaroLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pesaroLabel.setText(resourceMap.getString("pesaroLabel.text")); // NOI18N
        pesaroLabel.setToolTipText(resourceMap.getString("pesaroLabel.toolTipText")); // NOI18N
        pesaroLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        pesaroLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pesaroLabel.setName("pesaroLabel"); // NOI18N
        mapPanel1.add(pesaroLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 120, 30));

        viterboLabel.setFont(resourceMap.getFont("bolognaLabel.font")); // NOI18N
        viterboLabel.setForeground(resourceMap.getColor("bolognaLabel.foreground")); // NOI18N
        viterboLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        viterboLabel.setText(resourceMap.getString("viterboLabel.text")); // NOI18N
        viterboLabel.setToolTipText(resourceMap.getString("viterboLabel.toolTipText")); // NOI18N
        viterboLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        viterboLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viterboLabel.setName("viterboLabel"); // NOI18N
        mapPanel1.add(viterboLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 80, 40));

        lAquilaLabel.setFont(resourceMap.getFont("bolognaLabel.font")); // NOI18N
        lAquilaLabel.setForeground(resourceMap.getColor("bolognaLabel.foreground")); // NOI18N
        lAquilaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lAquilaLabel.setText(resourceMap.getString("lAquilaLabel.text")); // NOI18N
        lAquilaLabel.setToolTipText(resourceMap.getString("lAquilaLabel.toolTipText")); // NOI18N
        lAquilaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lAquilaLabel.setName("lAquilaLabel"); // NOI18N
        mapPanel1.add(lAquilaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 140, 30));

        latinaLabel.setFont(resourceMap.getFont("bolognaLabel.font")); // NOI18N
        latinaLabel.setForeground(resourceMap.getColor("bolognaLabel.foreground")); // NOI18N
        latinaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        latinaLabel.setText(resourceMap.getString("latinaLabel.text")); // NOI18N
        latinaLabel.setToolTipText(resourceMap.getString("latinaLabel.toolTipText")); // NOI18N
        latinaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        latinaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        latinaLabel.setName("latinaLabel"); // NOI18N
        mapPanel1.add(latinaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 60, 60));

        triesteLabel.setFont(resourceMap.getFont("bolognaLabel.font")); // NOI18N
        triesteLabel.setForeground(resourceMap.getColor("bolognaLabel.foreground")); // NOI18N
        triesteLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        triesteLabel.setText(resourceMap.getString("triesteLabel.text")); // NOI18N
        triesteLabel.setToolTipText(resourceMap.getString("triesteLabel.toolTipText")); // NOI18N
        triesteLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        triesteLabel.setName("triesteLabel"); // NOI18N
        mapPanel1.add(triesteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 130, 70));

        add(mapPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    

   
       
   

   
   
  

   /* public void updateAppliance(int troops_number, int region) {

        Territorio territorio=this.tavolo.getMappa().getTerritorio(region);
        String message="Il "+territorio.getOccupante().getNome()+" posiziona "+troops_number+" in "+territorio.getNome();
        this.informationPanel.appendActionInHistory(message);
        System.out.println("ricevuto messaggio di appliance per territorio "+territorio.getNome()+" di "+troops_number+" unita");
        if(tavolo.assegnaUnita(troops_number, territorio)){
            this.territoriLabels[region].setText(Integer.toString(territorio.getNumeroUnita()));
            this.informationPanel.updateDatiGiocatore(territorio.getOccupante());
        }else{
            System.out.println("errore comunicazione appliance");
            
        }
        //showInfo("Disposizione", message);
    }*/

 /*   public void updateAttack(int troops_number, int from, int to) {
        Territorio fromTerritorio=this.tavolo.getMappa().getTerritorio(from);
        Territorio toTerritorio=this.tavolo.getMappa().getTerritorio(to);
        Giocatore  attaccante=fromTerritorio.getOccupante();
        Giocatore difensore=toTerritorio.getOccupante();
        Azione azione=tavolo.preparaAttacco(fromTerritorio, toTerritorio);
        VirtualRisikoIIEndGameBox endGameBox;
        System.out.println("ricevuto messaggio di attacco da territorio "+fromTerritorio.getNome()+"a territorio "+toTerritorio.getNome()+" con "+troops_number+" unita");
            if(azione!=null){
                azione.setNumeroTruppe(troops_number);
                tavolo.eseguiAttacco((Attacco)azione);

                this.informationPanel.appendActionInHistory(azione.toString());
                this.setLabel(azione.getDaTerritorio());
                this.setLabel(azione.getaTerritorio());
                String message="Il "+fromTerritorio.getOccupante().getNome()+" attacca da "+fromTerritorio.getNome()+"\n"+" a "+toTerritorio.getNome()+"\n"+" con "+troops_number+" unita"+
                        "attacco : ";
                if(azione.isAttacco()){

                    //variabili per i dati di Luigi
                    int [] att={0,0,0};
                    int [] dif={0,0,0};

                    int[] a=((Attacco)azione).getPunteggio();
                    String s="";
                    for(int i=0;i<a.length;i++){
                        s=s+" - "+Integer.toString(a[i]);
                        att[i]=a[i];
                    }
                    this.informationPanel.appendActionInHistory(s);
                    message=message+s+"\n"+"difesa : " ;
                    a=((Attacco)azione).getPunteggioAvversario();
                     s="";
                    for(int i=0;i<a.length;i++){
                        s=s+" - "+Integer.toString(a[i]);
                        dif[i]=a[i];
                    }
                     message=message+s;
                    this.informationPanel.appendActionInHistory(s);

                    //lancia il panel di Luigi
                    new dadiGui("Attacco da "+azione.getDaTerritorio().getNome()+" a "+azione.getaTerritorio().getNome(),att[0],att[1],att[2],dif[0],dif[1],dif[2],attaccante.getID(),difensore.getID()).setVisible(true);
                

                } 

                //azione diversa da null::controllare stato obiettivi
                if(this.tavolo.controllaObiettivoGiocatore(this.tavolo.getGiocatoreCorrente())){

                   this.showEndFrame(tavolo.getGiocatori(), tavolo.getGiocatoreCorrente());
                }

            }else{
            System.out.println("errore comunicazione attacco");
            
        }

    }*/

 /*   public void updateMovement(int troops_number, int from, int to) {
        Territorio fromTerritorio=this.tavolo.getMappa().getTerritorio(from);
        Territorio toTerritorio=this.tavolo.getMappa().getTerritorio(to);
        System.out.println("Spostamento :Il "+tavolo.getGiocatoreCorrente()+" sposta da "+fromTerritorio.getNome()+" a "+toTerritorio.getNome()+" con "+troops_number+" unita");
        Azione azione=tavolo.preparaSpostamento(fromTerritorio, toTerritorio);
        VirtualRisikoIIEndGameBox endGameBox;
        if(azione!=null){
            azione.setNumeroTruppe(troops_number);
            tavolo.eseguiSpostamento((Spostamento) azione);

                this.informationPanel.appendActionInHistory(azione.toString());
                this.setLabel(azione.getDaTerritorio());
                this.setLabel(azione.getaTerritorio());

                

                //azione diversa da null::controllare stato obiettivi
                if(this.tavolo.controllaObiettivoGiocatore(this.tavolo.getGiocatoreCorrente())){

                    this.showEndFrame(tavolo.getGiocatori(), this.tavolo.getGiocatoreCorrente());
                }

            }

    }*/

    

    

   /* public void updateChangeCards(int card1, int card2, int card3) {

        Tavolo tavolo=Tavolo.getInstance();
        Giocatore g=tavolo.getGiocatoreCorrente();
        Carta c1=g.getCarta(card1);
        Carta c2=g.getCarta(card2);
        Carta c3=g.getCarta(card3);
        int rinforzi=Rinforzo.getRinfornzo(g, c1, c2, c3, tavolo.getMappa());
        g.setNumeroTruppe(g.getNumeroTruppe()+rinforzi);
        System.out.println("Ricevuta cambio dal "+g.getNome()+" con "+c1.getTerritorio().getNome()+" "+c2.getTerritorio().getNome()+" "+c3.getTerritorio().getNome());
        this.informationPanel.updateDatiGiocatore(g);
        List<Carta> carte=tavolo.getCarte();
        carte.add(c1);
        carte.add(c2);
        carte.add(c3);

    }*/

   

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agrigentoLabel;
    private javax.swing.JLabel alessandriaLabel;
    private javax.swing.JLabel anconaLabel;
    private javax.swing.JLabel aostaaLabel;
    private javax.swing.JLabel bariLabel;
    private javax.swing.JLabel bergamoLabel;
    private javax.swing.JLabel bolognaLabel;
    private javax.swing.JLabel bresciaLabel;
    private javax.swing.JLabel cagliariLabel;
    private javax.swing.JLabel campobassoLabel;
    private javax.swing.JLabel catanzaroLabel;
    private javax.swing.JLabel cuneoLabel;
    private javax.swing.JLabel firenzeLabel;
    private javax.swing.JLabel foggiaLabel;
    private javax.swing.JLabel genovaLabel;
    private javax.swing.JLabel imperiaLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lAquilaLabel;
    private javax.swing.JLabel latinaLabel;
    private javax.swing.JLabel lecceLabel;
    private virtualrisikoii.Map.italia.MapPanel mapPanel1;
    private javax.swing.JLabel messinaLabel;
    private javax.swing.JLabel milanoLabel;
    private javax.swing.JLabel napoliLabel;
    private javax.swing.JLabel nuoroLabel;
    private javax.swing.JLabel palermoLabel;
    private javax.swing.JLabel parmaLabel;
    private javax.swing.JLabel perugiaLabel;
    private javax.swing.JLabel pesaroLabel;
    private javax.swing.JLabel pisaLabel;
    private javax.swing.JLabel potenzaLabel;
    private javax.swing.JLabel reggioCalabriaLabel;
    private javax.swing.JLabel riminiLabel;
    private javax.swing.JLabel romaLabel;
    private javax.swing.JLabel salernoLabel;
    private javax.swing.JLabel sassariLabel;
    private javax.swing.JLabel sienaLabel;
    private javax.swing.JLabel torinoLabel;
    private javax.swing.JLabel trapaniLabel;
    private javax.swing.JLabel trentoLabel;
    private javax.swing.JLabel triesteLabel;
    private javax.swing.JLabel veneziaLabel;
    private javax.swing.JLabel veronaLabel;
    private javax.swing.JLabel viterboLabel;
    // End of variables declaration//GEN-END:variables


}
