/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClassicalMapPanel.java
 *
 * Created on 20-apr-2011, 22.08.01
 */

package virtualrisikoii.Map.classical;

import javax.swing.JLabel;
import services.GameController;
import virtualrisikoii.XMapPanel;

/**
 *
 * @author root
 */
public class ClassicalMapPanel extends   XMapPanel{

    


    /** Creates new form ClassicalMapPanel */
    public ClassicalMapPanel() {
        gameController=GameController.getInstance();
        gameController.setMapListener(this);
        gameController.setTroopsSelector(this);
        gameController.setVictoryListener(this);
        gameController.setCardListener(this);
        initComponents();
        territoriLabels=new JLabel[42];
        territoriLabels[0]=alaskaLabel;
        territoriLabels[1]=territorioNOLabel;
        territoriLabels[2]=groenlandiaLabel;
        territoriLabels[3]=albertaLabel;
        territoriLabels[4]=ontarioLabel;
        territoriLabels[5]=quebecLabel;
        territoriLabels[6]=statiUnitiOccLabel;
        territoriLabels[7]=statiUnitiOriLabel;
        territoriLabels[8]=messicoLabel;
        territoriLabels[9]=venezuelaLabel;
        territoriLabels[10]=peruLabel;
        territoriLabels[11]=brasileLabel;
        territoriLabels[12]=argentinaLabel;
        territoriLabels[13]=islandaLabel;
        territoriLabels[14]=scandinaviaLabel;
        territoriLabels[15]=granBretagnaLabel;
        territoriLabels[16]=europaSettentrionaleLabel;
        territoriLabels[17]=europaOccidentaleLabel;
        territoriLabels[18]=europaMeridionaleLabel;
        territoriLabels[19]=ucrainaLabel;
        territoriLabels[20]=africaNordLabel;
        territoriLabels[21]=egittoLabel;
        territoriLabels[22]=congoLabel;
        territoriLabels[23]=africaOrientaleLabel;
        territoriLabels[24]=africaSudLabel;
        territoriLabels[25]=madagascarLabel;
        territoriLabels[26]=uraliLabel;
        territoriLabels[27]=siberiaLabel;
        territoriLabels[28]=jacuziaLabel;
        territoriLabels[29]=citaLabel;
        territoriLabels[30]=kamchatkaLabel;
        territoriLabels[31]=giapponeLabel;
        territoriLabels[32]=mongoliaLabel;
        territoriLabels[33]=kazakistanLabel;
        territoriLabels[34]=medioOrienteLabel;
        territoriLabels[35]=indiaLabel;
        territoriLabels[36]=cinaLabel;
        territoriLabels[37]=siamLabel;
        territoriLabels[38]=indonesiaLabel;
        territoriLabels[39]=nuovaGuineaLabel;
        territoriLabels[40]=australiaOrientaleLabel;
        territoriLabels[41]=australiaOccidentaleLabel;

        LabelSelector selector=new LabelSelector();
        for(int i=0;i<territoriLabels.length;i++){
            this.territoriLabels[i].addMouseListener(selector);
        }

        initIconPlayers();
        gameController.initMap();


        
    }

   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        mapPanel1 = new virtualrisikoii.Map.classical.MapPanel();
        scandinaviaLabel = new javax.swing.JLabel();
        ucrainaLabel = new javax.swing.JLabel();
        granBretagnaLabel = new javax.swing.JLabel();
        uraliLabel = new javax.swing.JLabel();
        siberiaLabel = new javax.swing.JLabel();
        jacuziaLabel = new javax.swing.JLabel();
        kamchatkaLabel = new javax.swing.JLabel();
        alaskaLabel = new javax.swing.JLabel();
        ontarioLabel = new javax.swing.JLabel();
        citaLabel = new javax.swing.JLabel();
        territorioNOLabel = new javax.swing.JLabel();
        albertaLabel = new javax.swing.JLabel();
        statiUnitiOccLabel = new javax.swing.JLabel();
        quebecLabel = new javax.swing.JLabel();
        groenlandiaLabel = new javax.swing.JLabel();
        statiUnitiOriLabel = new javax.swing.JLabel();
        messicoLabel = new javax.swing.JLabel();
        venezuelaLabel = new javax.swing.JLabel();
        brasileLabel = new javax.swing.JLabel();
        peruLabel = new javax.swing.JLabel();
        argentinaLabel = new javax.swing.JLabel();
        australiaOrientaleLabel = new javax.swing.JLabel();
        australiaOccidentaleLabel = new javax.swing.JLabel();
        nuovaGuineaLabel = new javax.swing.JLabel();
        indonesiaLabel = new javax.swing.JLabel();
        siamLabel = new javax.swing.JLabel();
        indiaLabel = new javax.swing.JLabel();
        cinaLabel = new javax.swing.JLabel();
        mongoliaLabel = new javax.swing.JLabel();
        giapponeLabel = new javax.swing.JLabel();
        kazakistanLabel = new javax.swing.JLabel();
        medioOrienteLabel = new javax.swing.JLabel();
        europaSettentrionaleLabel = new javax.swing.JLabel();
        europaMeridionaleLabel = new javax.swing.JLabel();
        europaOccidentaleLabel = new javax.swing.JLabel();
        egittoLabel = new javax.swing.JLabel();
        africaOrientaleLabel = new javax.swing.JLabel();
        africaNordLabel = new javax.swing.JLabel();
        congoLabel = new javax.swing.JLabel();
        africaSudLabel = new javax.swing.JLabel();
        madagascarLabel = new javax.swing.JLabel();
        islandaLabel = new javax.swing.JLabel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(ClassicalMapPanel.class);
        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.BorderLayout());

        mapPanel1.setName("mapPanel1"); // NOI18N

        scandinaviaLabel.setFont(resourceMap.getFont("europaMeridionaleLabel.font")); // NOI18N
        scandinaviaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        scandinaviaLabel.setText(resourceMap.getString("scandinaviaLabel.text")); // NOI18N
        scandinaviaLabel.setToolTipText(resourceMap.getString("scandinaviaLabel.toolTipText")); // NOI18N
        scandinaviaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        scandinaviaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        scandinaviaLabel.setName("scandinaviaLabel"); // NOI18N

        ucrainaLabel.setFont(resourceMap.getFont("europaMeridionaleLabel.font")); // NOI18N
        ucrainaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ucrainaLabel.setText(resourceMap.getString("ucrainaLabel.text")); // NOI18N
        ucrainaLabel.setToolTipText(resourceMap.getString("ucrainaLabel.toolTipText")); // NOI18N
        ucrainaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ucrainaLabel.setName("ucrainaLabel"); // NOI18N

        granBretagnaLabel.setFont(resourceMap.getFont("europaMeridionaleLabel.font")); // NOI18N
        granBretagnaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        granBretagnaLabel.setText(resourceMap.getString("granBretagnaLabel.text")); // NOI18N
        granBretagnaLabel.setToolTipText(resourceMap.getString("granBretagnaLabel.toolTipText")); // NOI18N
        granBretagnaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        granBretagnaLabel.setName("granBretagnaLabel"); // NOI18N

        uraliLabel.setFont(resourceMap.getFont("europaMeridionaleLabel.font")); // NOI18N
        uraliLabel.setText(resourceMap.getString("uraliLabel.text")); // NOI18N
        uraliLabel.setToolTipText(resourceMap.getString("uraliLabel.toolTipText")); // NOI18N
        uraliLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        uraliLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        uraliLabel.setName("uraliLabel"); // NOI18N

        siberiaLabel.setFont(resourceMap.getFont("europaMeridionaleLabel.font")); // NOI18N
        siberiaLabel.setText(resourceMap.getString("siberiaLabel.text")); // NOI18N
        siberiaLabel.setToolTipText(resourceMap.getString("siberiaLabel.toolTipText")); // NOI18N
        siberiaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        siberiaLabel.setName("siberiaLabel"); // NOI18N

        jacuziaLabel.setFont(resourceMap.getFont("europaMeridionaleLabel.font")); // NOI18N
        jacuziaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jacuziaLabel.setText(resourceMap.getString("jacuziaLabel.text")); // NOI18N
        jacuziaLabel.setToolTipText(resourceMap.getString("jacuziaLabel.toolTipText")); // NOI18N
        jacuziaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jacuziaLabel.setName("jacuziaLabel"); // NOI18N

        kamchatkaLabel.setFont(resourceMap.getFont("europaMeridionaleLabel.font")); // NOI18N
        kamchatkaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        kamchatkaLabel.setText(resourceMap.getString("kamchatkaLabel.text")); // NOI18N
        kamchatkaLabel.setToolTipText(resourceMap.getString("kamchatkaLabel.toolTipText")); // NOI18N
        kamchatkaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kamchatkaLabel.setName("kamchatkaLabel"); // NOI18N

        alaskaLabel.setFont(resourceMap.getFont("europaMeridionaleLabel.font")); // NOI18N
        alaskaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        alaskaLabel.setText(resourceMap.getString("alaskaLabel.text")); // NOI18N
        alaskaLabel.setToolTipText(resourceMap.getString("alaskaLabel.toolTipText")); // NOI18N
        alaskaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        alaskaLabel.setName("alaskaLabel"); // NOI18N

        ontarioLabel.setFont(resourceMap.getFont("europaMeridionaleLabel.font")); // NOI18N
        ontarioLabel.setText(resourceMap.getString("ontarioLabel.text")); // NOI18N
        ontarioLabel.setToolTipText(resourceMap.getString("ontarioLabel.toolTipText")); // NOI18N
        ontarioLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        ontarioLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ontarioLabel.setName("ontarioLabel"); // NOI18N

        citaLabel.setFont(resourceMap.getFont("europaMeridionaleLabel.font")); // NOI18N
        citaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        citaLabel.setText(resourceMap.getString("citaLabel.text")); // NOI18N
        citaLabel.setToolTipText(resourceMap.getString("citaLabel.toolTipText")); // NOI18N
        citaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        citaLabel.setName("citaLabel"); // NOI18N

        territorioNOLabel.setFont(resourceMap.getFont("europaMeridionaleLabel.font")); // NOI18N
        territorioNOLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        territorioNOLabel.setText(resourceMap.getString("territorioNOLabel.text")); // NOI18N
        territorioNOLabel.setToolTipText(resourceMap.getString("territorioNOLabel.toolTipText")); // NOI18N
        territorioNOLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        territorioNOLabel.setName("territorioNOLabel"); // NOI18N

        albertaLabel.setFont(resourceMap.getFont("europaMeridionaleLabel.font")); // NOI18N
        albertaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        albertaLabel.setText(resourceMap.getString("albertaLabel.text")); // NOI18N
        albertaLabel.setToolTipText(resourceMap.getString("albertaLabel.toolTipText")); // NOI18N
        albertaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        albertaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        albertaLabel.setName("albertaLabel"); // NOI18N

        statiUnitiOccLabel.setFont(resourceMap.getFont("europaMeridionaleLabel.font")); // NOI18N
        statiUnitiOccLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statiUnitiOccLabel.setText(resourceMap.getString("statiUnitiOccLabel.text")); // NOI18N
        statiUnitiOccLabel.setToolTipText(resourceMap.getString("statiUnitiOccLabel.toolTipText")); // NOI18N
        statiUnitiOccLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        statiUnitiOccLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        statiUnitiOccLabel.setName("statiUnitiOccLabel"); // NOI18N

        quebecLabel.setFont(resourceMap.getFont("europaMeridionaleLabel.font")); // NOI18N
        quebecLabel.setText(resourceMap.getString("quebecLabel.text")); // NOI18N
        quebecLabel.setToolTipText(resourceMap.getString("quebecLabel.toolTipText")); // NOI18N
        quebecLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        quebecLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quebecLabel.setName("quebecLabel"); // NOI18N

        groenlandiaLabel.setFont(resourceMap.getFont("europaMeridionaleLabel.font")); // NOI18N
        groenlandiaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        groenlandiaLabel.setText(resourceMap.getString("groenlandiaLabel.text")); // NOI18N
        groenlandiaLabel.setToolTipText(resourceMap.getString("groenlandiaLabel.toolTipText")); // NOI18N
        groenlandiaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        groenlandiaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        groenlandiaLabel.setName("groenlandiaLabel"); // NOI18N

        statiUnitiOriLabel.setFont(resourceMap.getFont("europaMeridionaleLabel.font")); // NOI18N
        statiUnitiOriLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statiUnitiOriLabel.setText(resourceMap.getString("statiUnitiOriLabel.text")); // NOI18N
        statiUnitiOriLabel.setToolTipText(resourceMap.getString("statiUnitiOriLabel.toolTipText")); // NOI18N
        statiUnitiOriLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        statiUnitiOriLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        statiUnitiOriLabel.setName("statiUnitiOriLabel"); // NOI18N

        messicoLabel.setFont(resourceMap.getFont("europaMeridionaleLabel.font")); // NOI18N
        messicoLabel.setText(resourceMap.getString("messicoLabel.text")); // NOI18N
        messicoLabel.setToolTipText(resourceMap.getString("messicoLabel.toolTipText")); // NOI18N
        messicoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        messicoLabel.setName("messicoLabel"); // NOI18N

        venezuelaLabel.setFont(resourceMap.getFont("europaMeridionaleLabel.font")); // NOI18N
        venezuelaLabel.setText(resourceMap.getString("venezuelaLabel.text")); // NOI18N
        venezuelaLabel.setToolTipText(resourceMap.getString("venezuelaLabel.toolTipText")); // NOI18N
        venezuelaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        venezuelaLabel.setName("venezuelaLabel"); // NOI18N

        brasileLabel.setFont(resourceMap.getFont("europaMeridionaleLabel.font")); // NOI18N
        brasileLabel.setText(resourceMap.getString("brasileLabel.text")); // NOI18N
        brasileLabel.setToolTipText(resourceMap.getString("brasileLabel.toolTipText")); // NOI18N
        brasileLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        brasileLabel.setName("brasileLabel"); // NOI18N

        peruLabel.setFont(resourceMap.getFont("europaMeridionaleLabel.font")); // NOI18N
        peruLabel.setText(resourceMap.getString("peruLabel.text")); // NOI18N
        peruLabel.setToolTipText(resourceMap.getString("peruLabel.toolTipText")); // NOI18N
        peruLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        peruLabel.setName("peruLabel"); // NOI18N

        argentinaLabel.setFont(resourceMap.getFont("europaMeridionaleLabel.font")); // NOI18N
        argentinaLabel.setText(resourceMap.getString("argentinaLabel.text")); // NOI18N
        argentinaLabel.setToolTipText(resourceMap.getString("argentinaLabel.toolTipText")); // NOI18N
        argentinaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        argentinaLabel.setName("argentinaLabel"); // NOI18N

        australiaOrientaleLabel.setFont(resourceMap.getFont("europaMeridionaleLabel.font")); // NOI18N
        australiaOrientaleLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        australiaOrientaleLabel.setText(resourceMap.getString("australiaOrientaleLabel.text")); // NOI18N
        australiaOrientaleLabel.setToolTipText(resourceMap.getString("australiaOrientaleLabel.toolTipText")); // NOI18N
        australiaOrientaleLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        australiaOrientaleLabel.setName("australiaOrientaleLabel"); // NOI18N

        australiaOccidentaleLabel.setFont(resourceMap.getFont("europaMeridionaleLabel.font")); // NOI18N
        australiaOccidentaleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        australiaOccidentaleLabel.setText(resourceMap.getString("australiaOccidentaleLabel.text")); // NOI18N
        australiaOccidentaleLabel.setToolTipText(resourceMap.getString("australiaOccidentaleLabel.toolTipText")); // NOI18N
        australiaOccidentaleLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        australiaOccidentaleLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        australiaOccidentaleLabel.setName("australiaOccidentaleLabel"); // NOI18N

        nuovaGuineaLabel.setFont(resourceMap.getFont("europaMeridionaleLabel.font")); // NOI18N
        nuovaGuineaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nuovaGuineaLabel.setText(resourceMap.getString("nuovaGuineaLabel.text")); // NOI18N
        nuovaGuineaLabel.setToolTipText(resourceMap.getString("nuovaGuineaLabel.toolTipText")); // NOI18N
        nuovaGuineaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nuovaGuineaLabel.setName("nuovaGuineaLabel"); // NOI18N

        indonesiaLabel.setFont(resourceMap.getFont("europaMeridionaleLabel.font")); // NOI18N
        indonesiaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        indonesiaLabel.setText(resourceMap.getString("indonesiaLabel.text")); // NOI18N
        indonesiaLabel.setToolTipText(resourceMap.getString("indonesiaLabel.toolTipText")); // NOI18N
        indonesiaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        indonesiaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        indonesiaLabel.setName("indonesiaLabel"); // NOI18N

        siamLabel.setFont(resourceMap.getFont("europaMeridionaleLabel.font")); // NOI18N
        siamLabel.setText(resourceMap.getString("siamLabel.text")); // NOI18N
        siamLabel.setToolTipText(resourceMap.getString("siamLabel.toolTipText")); // NOI18N
        siamLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        siamLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        siamLabel.setName("siamLabel"); // NOI18N

        indiaLabel.setFont(resourceMap.getFont("europaMeridionaleLabel.font")); // NOI18N
        indiaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        indiaLabel.setText(resourceMap.getString("indiaLabel.text")); // NOI18N
        indiaLabel.setToolTipText(resourceMap.getString("indiaLabel.toolTipText")); // NOI18N
        indiaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        indiaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        indiaLabel.setName("indiaLabel"); // NOI18N

        cinaLabel.setFont(resourceMap.getFont("europaMeridionaleLabel.font")); // NOI18N
        cinaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cinaLabel.setText(resourceMap.getString("cinaLabel.text")); // NOI18N
        cinaLabel.setToolTipText(resourceMap.getString("cinaLabel.toolTipText")); // NOI18N
        cinaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cinaLabel.setName("cinaLabel"); // NOI18N

        mongoliaLabel.setFont(resourceMap.getFont("europaMeridionaleLabel.font")); // NOI18N
        mongoliaLabel.setText(resourceMap.getString("mongoliaLabel.text")); // NOI18N
        mongoliaLabel.setToolTipText(resourceMap.getString("mongoliaLabel.toolTipText")); // NOI18N
        mongoliaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mongoliaLabel.setName("mongoliaLabel"); // NOI18N

        giapponeLabel.setFont(resourceMap.getFont("europaMeridionaleLabel.font")); // NOI18N
        giapponeLabel.setText(resourceMap.getString("giapponeLabel.text")); // NOI18N
        giapponeLabel.setToolTipText(resourceMap.getString("giapponeLabel.toolTipText")); // NOI18N
        giapponeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        giapponeLabel.setName("giapponeLabel"); // NOI18N

        kazakistanLabel.setFont(resourceMap.getFont("europaMeridionaleLabel.font")); // NOI18N
        kazakistanLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kazakistanLabel.setText(resourceMap.getString("kazakistanLabel.text")); // NOI18N
        kazakistanLabel.setToolTipText(resourceMap.getString("kazakistanLabel.toolTipText")); // NOI18N
        kazakistanLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        kazakistanLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kazakistanLabel.setName("kazakistanLabel"); // NOI18N

        medioOrienteLabel.setFont(resourceMap.getFont("europaMeridionaleLabel.font")); // NOI18N
        medioOrienteLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        medioOrienteLabel.setText(resourceMap.getString("medioOrienteLabel.text")); // NOI18N
        medioOrienteLabel.setToolTipText(resourceMap.getString("medioOrienteLabel.toolTipText")); // NOI18N
        medioOrienteLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        medioOrienteLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        medioOrienteLabel.setName("medioOrienteLabel"); // NOI18N

        europaSettentrionaleLabel.setFont(resourceMap.getFont("europaMeridionaleLabel.font")); // NOI18N
        europaSettentrionaleLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        europaSettentrionaleLabel.setText(resourceMap.getString("europaSettentrionaleLabel.text")); // NOI18N
        europaSettentrionaleLabel.setToolTipText(resourceMap.getString("europaSettentrionaleLabel.toolTipText")); // NOI18N
        europaSettentrionaleLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        europaSettentrionaleLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        europaSettentrionaleLabel.setName("europaSettentrionaleLabel"); // NOI18N

        europaMeridionaleLabel.setFont(resourceMap.getFont("europaMeridionaleLabel.font")); // NOI18N
        europaMeridionaleLabel.setText(resourceMap.getString("europaMeridionaleLabel.text")); // NOI18N
        europaMeridionaleLabel.setToolTipText(resourceMap.getString("europaMeridionaleLabel.toolTipText")); // NOI18N
        europaMeridionaleLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        europaMeridionaleLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        europaMeridionaleLabel.setName("europaMeridionaleLabel"); // NOI18N

        europaOccidentaleLabel.setFont(resourceMap.getFont("europaMeridionaleLabel.font")); // NOI18N
        europaOccidentaleLabel.setText(resourceMap.getString("europaOccidentaleLabel.text")); // NOI18N
        europaOccidentaleLabel.setToolTipText(resourceMap.getString("europaOccidentaleLabel.toolTipText")); // NOI18N
        europaOccidentaleLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        europaOccidentaleLabel.setName("europaOccidentaleLabel"); // NOI18N

        egittoLabel.setFont(resourceMap.getFont("europaMeridionaleLabel.font")); // NOI18N
        egittoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        egittoLabel.setText(resourceMap.getString("egittoLabel.text")); // NOI18N
        egittoLabel.setToolTipText(resourceMap.getString("egittoLabel.toolTipText")); // NOI18N
        egittoLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        egittoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        egittoLabel.setName("egittoLabel"); // NOI18N

        africaOrientaleLabel.setFont(resourceMap.getFont("europaMeridionaleLabel.font")); // NOI18N
        africaOrientaleLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        africaOrientaleLabel.setText(resourceMap.getString("africaOrientaleLabel.text")); // NOI18N
        africaOrientaleLabel.setToolTipText(resourceMap.getString("africaOrientaleLabel.toolTipText")); // NOI18N
        africaOrientaleLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        africaOrientaleLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        africaOrientaleLabel.setName("africaOrientaleLabel"); // NOI18N

        africaNordLabel.setFont(resourceMap.getFont("europaMeridionaleLabel.font")); // NOI18N
        africaNordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        africaNordLabel.setText(resourceMap.getString("africaNordLabel.text")); // NOI18N
        africaNordLabel.setToolTipText(resourceMap.getString("africaNordLabel.toolTipText")); // NOI18N
        africaNordLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        africaNordLabel.setName("africaNordLabel"); // NOI18N

        congoLabel.setFont(resourceMap.getFont("europaMeridionaleLabel.font")); // NOI18N
        congoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        congoLabel.setText(resourceMap.getString("congoLabel.text")); // NOI18N
        congoLabel.setToolTipText(resourceMap.getString("congoLabel.toolTipText")); // NOI18N
        congoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        congoLabel.setName("congoLabel"); // NOI18N

        africaSudLabel.setFont(resourceMap.getFont("europaMeridionaleLabel.font")); // NOI18N
        africaSudLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        africaSudLabel.setText(resourceMap.getString("africaSudLabel.text")); // NOI18N
        africaSudLabel.setToolTipText(resourceMap.getString("africaSudLabel.toolTipText")); // NOI18N
        africaSudLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        africaSudLabel.setName("africaSudLabel"); // NOI18N

        madagascarLabel.setFont(resourceMap.getFont("europaMeridionaleLabel.font")); // NOI18N
        madagascarLabel.setText(resourceMap.getString("madagascarLabel.text")); // NOI18N
        madagascarLabel.setToolTipText(resourceMap.getString("madagascarLabel.toolTipText")); // NOI18N
        madagascarLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        madagascarLabel.setName("madagascarLabel"); // NOI18N

        islandaLabel.setFont(resourceMap.getFont("europaMeridionaleLabel.font")); // NOI18N
        islandaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        islandaLabel.setText(resourceMap.getString("islandaLabel.text")); // NOI18N
        islandaLabel.setToolTipText(resourceMap.getString("islandaLabel.toolTipText")); // NOI18N
        islandaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        islandaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        islandaLabel.setName("islandaLabel"); // NOI18N

        javax.swing.GroupLayout mapPanel1Layout = new javax.swing.GroupLayout(mapPanel1);
        mapPanel1.setLayout(mapPanel1Layout);
        mapPanel1Layout.setHorizontalGroup(
            mapPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mapPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(mapPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mapPanel1Layout.createSequentialGroup()
                        .addGroup(mapPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mapPanel1Layout.createSequentialGroup()
                                .addComponent(islandaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(scandinaviaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mapPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(granBretagnaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(europaSettentrionaleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mapPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(europaOccidentaleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(europaMeridionaleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(africaNordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(mapPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mapPanel1Layout.createSequentialGroup()
                                .addComponent(ucrainaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(mapPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mapPanel1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(uraliLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(kazakistanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(siberiaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addGroup(mapPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mapPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jacuziaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(citaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mongoliaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(mapPanel1Layout.createSequentialGroup()
                                .addGroup(mapPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mapPanel1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(medioOrienteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(africaOrientaleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(mapPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mapPanel1Layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(cinaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mapPanel1Layout.createSequentialGroup()
                                        .addComponent(indiaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(siamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(mapPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(egittoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mapPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(congoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mapPanel1Layout.createSequentialGroup()
                        .addGap(410, 410, 410)
                        .addComponent(indonesiaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(mapPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mapPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(kamchatkaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(giapponeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mapPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(nuovaGuineaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(alaskaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(mapPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mapPanel1Layout.createSequentialGroup()
                        .addComponent(territorioNOLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(groenlandiaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mapPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(albertaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ontarioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(quebecLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mapPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(statiUnitiOccLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(statiUnitiOriLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mapPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(messicoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mapPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(mapPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mapPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(brasileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(venezuelaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mapPanel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(peruLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(mapPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(africaSudLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(madagascarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180)
                .addComponent(australiaOccidentaleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(australiaOrientaleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(270, 270, 270)
                .addComponent(argentinaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        mapPanel1Layout.setVerticalGroup(
            mapPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mapPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(mapPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mapPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(mapPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mapPanel1Layout.createSequentialGroup()
                                .addGroup(mapPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mapPanel1Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(mapPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(islandaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(mapPanel1Layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(scandinaviaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(mapPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(granBretagnaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(mapPanel1Layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addComponent(europaSettentrionaleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(10, 10, 10)
                                        .addGroup(mapPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(europaOccidentaleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(europaMeridionaleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(40, 40, 40)
                                        .addComponent(africaNordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mapPanel1Layout.createSequentialGroup()
                                        .addGroup(mapPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(mapPanel1Layout.createSequentialGroup()
                                                .addGap(70, 70, 70)
                                                .addComponent(ucrainaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(mapPanel1Layout.createSequentialGroup()
                                                .addGap(80, 80, 80)
                                                .addComponent(uraliLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30)
                                                .addComponent(kazakistanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(siberiaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(mapPanel1Layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(jacuziaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(20, 20, 20)
                                                .addComponent(citaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30)
                                                .addComponent(mongoliaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(10, 10, 10)
                                        .addGroup(mapPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(mapPanel1Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(medioOrienteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(50, 50, 50)
                                                .addComponent(africaOrientaleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(mapPanel1Layout.createSequentialGroup()
                                                .addComponent(cinaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(10, 10, 10)
                                                .addGroup(mapPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(indiaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(mapPanel1Layout.createSequentialGroup()
                                                        .addGap(30, 30, 30)
                                                        .addComponent(siamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addGroup(mapPanel1Layout.createSequentialGroup()
                                        .addGap(270, 270, 270)
                                        .addComponent(egittoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(20, 20, 20)
                                .addComponent(congoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mapPanel1Layout.createSequentialGroup()
                                .addGap(390, 390, 390)
                                .addComponent(indonesiaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(mapPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(kamchatkaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(giapponeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(190, 190, 190)
                        .addComponent(nuovaGuineaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mapPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(alaskaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mapPanel1Layout.createSequentialGroup()
                        .addGroup(mapPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mapPanel1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(territorioNOLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(groenlandiaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(mapPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(albertaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ontarioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quebecLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(mapPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statiUnitiOccLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mapPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(statiUnitiOriLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(messicoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(mapPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mapPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(brasileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(venezuelaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(peruLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(mapPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mapPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(africaSudLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(madagascarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mapPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(australiaOccidentaleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mapPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(australiaOrientaleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(argentinaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        add(mapPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

   
   /* public void updateAppliance(int troops_number, int region) {

        Territorio territorio=this.tavolo.getMappa().getTerritorio(region);
        String message="Il "+territorio.getOccupante().getNome()+" posiziona "+troops_number+" in "+territorio.getNome();
        this.informationPanel.appendActionInHistory(message);
        System.out.println("ricevuto messaggio di appliance per territorio "+territorio.getNome()+" di "+troops_number+" unita");
        if(tavolo.assegnaUnita(troops_number, territorio)){
            this.territoriLabels[region].setText(Integer.toString(territorio.getNumeroUnita()));
            this.informationPanel.updateDatiGiocatore(territorio.getOccupante());
        }else{
            System.out.println("errore comunicazione appliance");
            
        }
        //showInfo("Disposizione", message);
    }*/

 /*   public void updateAttack(int troops_number, int from, int to) {
        Territorio fromTerritorio=this.tavolo.getMappa().getTerritorio(from);
        Territorio toTerritorio=this.tavolo.getMappa().getTerritorio(to);
        Giocatore  attaccante=fromTerritorio.getOccupante();
        Giocatore difensore=toTerritorio.getOccupante();
        Azione azione=tavolo.preparaAttacco(fromTerritorio, toTerritorio);
        VirtualRisikoIIEndGameBox endGameBox;
        System.out.println("ricevuto messaggio di attacco da territorio "+fromTerritorio.getNome()+"a territorio "+toTerritorio.getNome()+" con "+troops_number+" unita");
            if(azione!=null){
                azione.setNumeroTruppe(troops_number);
                tavolo.eseguiAttacco((Attacco)azione);

                this.informationPanel.appendActionInHistory(azione.toString());
                this.setLabel(azione.getDaTerritorio());
                this.setLabel(azione.getaTerritorio());
                String message="Il "+fromTerritorio.getOccupante().getNome()+" attacca da "+fromTerritorio.getNome()+"\n"+" a "+toTerritorio.getNome()+"\n"+" con "+troops_number+" unita"+
                        "attacco : ";
                if(azione.isAttacco()){

                    //variabili per i dati di Luigi
                    int [] att={0,0,0};
                    int [] dif={0,0,0};

                    int[] a=((Attacco)azione).getPunteggio();
                    String s="";
                    for(int i=0;i<a.length;i++){
                        s=s+" - "+Integer.toString(a[i]);
                        att[i]=a[i];
                    }
                    this.informationPanel.appendActionInHistory(s);
                    message=message+s+"\n"+"difesa : " ;
                    a=((Attacco)azione).getPunteggioAvversario();
                     s="";
                    for(int i=0;i<a.length;i++){
                        s=s+" - "+Integer.toString(a[i]);
                        dif[i]=a[i];
                    }
                     message=message+s;
                    this.informationPanel.appendActionInHistory(s);

                    //lancia il panel di Luigi
                    new dadiGui("Attacco da "+azione.getDaTerritorio().getNome()+" a "+azione.getaTerritorio().getNome(),att[0],att[1],att[2],dif[0],dif[1],dif[2],attaccante.getID(),difensore.getID()).setVisible(true);
                

                }

                //azione diversa da null::controllare stato obiettivi
                if(this.tavolo.controllaObiettivoGiocatore(this.tavolo.getGiocatoreCorrente())){

                   this.showEndFrame(tavolo.getGiocatori(), tavolo.getGiocatoreCorrente());
                }

            }else{
            System.out.println("errore comunicazione attacco");
            
        }

    }*/

 /*   public void updateMovement(int troops_number, int from, int to) {
        Territorio fromTerritorio=this.tavolo.getMappa().getTerritorio(from);
        Territorio toTerritorio=this.tavolo.getMappa().getTerritorio(to);
        System.out.println("Spostamento :Il "+tavolo.getGiocatoreCorrente()+" sposta da "+fromTerritorio.getNome()+" a "+toTerritorio.getNome()+" con "+troops_number+" unita");
        Azione azione=tavolo.preparaSpostamento(fromTerritorio, toTerritorio);
        VirtualRisikoIIEndGameBox endGameBox;
        if(azione!=null){
            azione.setNumeroTruppe(troops_number);
            tavolo.eseguiSpostamento((Spostamento) azione);

                this.informationPanel.appendActionInHistory(azione.toString());
                this.setLabel(azione.getDaTerritorio());
                this.setLabel(azione.getaTerritorio());

                

                //azione diversa da null::controllare stato obiettivi
                if(this.tavolo.controllaObiettivoGiocatore(this.tavolo.getGiocatoreCorrente())){

                    this.showEndFrame(tavolo.getGiocatori(), this.tavolo.getGiocatoreCorrente());
                }

            }

    }*/

   
   /* public void updateChangeCards(int card1, int card2, int card3) {

        Tavolo tavolo=Tavolo.getInstance();
        Giocatore g=tavolo.getGiocatoreCorrente();
        Carta c1=g.getCarta(card1);
        Carta c2=g.getCarta(card2);
        Carta c3=g.getCarta(card3);
        int rinforzi=Rinforzo.getRinfornzo(g, c1, c2, c3, tavolo.getMappa());
        g.setNumeroTruppe(g.getNumeroTruppe()+rinforzi);
        System.out.println("Ricevuta cambio dal "+g.getNome()+" con "+c1.getTerritorio().getNome()+" "+c2.getTerritorio().getNome()+" "+c3.getTerritorio().getNome());
        this.informationPanel.updateDatiGiocatore(g);
        List<Carta> carte=tavolo.getCarte();
        carte.add(c1);
        carte.add(c2);
        carte.add(c3);

    }*/

  

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel africaNordLabel;
    private javax.swing.JLabel africaOrientaleLabel;
    private javax.swing.JLabel africaSudLabel;
    private javax.swing.JLabel alaskaLabel;
    private javax.swing.JLabel albertaLabel;
    private javax.swing.JLabel argentinaLabel;
    private javax.swing.JLabel australiaOccidentaleLabel;
    private javax.swing.JLabel australiaOrientaleLabel;
    private javax.swing.JLabel brasileLabel;
    private javax.swing.JLabel cinaLabel;
    private javax.swing.JLabel citaLabel;
    private javax.swing.JLabel congoLabel;
    private javax.swing.JLabel egittoLabel;
    private javax.swing.JLabel europaMeridionaleLabel;
    private javax.swing.JLabel europaOccidentaleLabel;
    private javax.swing.JLabel europaSettentrionaleLabel;
    private javax.swing.JLabel giapponeLabel;
    private javax.swing.JLabel granBretagnaLabel;
    private javax.swing.JLabel groenlandiaLabel;
    private javax.swing.JLabel indiaLabel;
    private javax.swing.JLabel indonesiaLabel;
    private javax.swing.JLabel islandaLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jacuziaLabel;
    private javax.swing.JLabel kamchatkaLabel;
    private javax.swing.JLabel kazakistanLabel;
    private javax.swing.JLabel madagascarLabel;
    private virtualrisikoii.Map.classical.MapPanel mapPanel1;
    private javax.swing.JLabel medioOrienteLabel;
    private javax.swing.JLabel messicoLabel;
    private javax.swing.JLabel mongoliaLabel;
    private javax.swing.JLabel nuovaGuineaLabel;
    private javax.swing.JLabel ontarioLabel;
    private javax.swing.JLabel peruLabel;
    private javax.swing.JLabel quebecLabel;
    private javax.swing.JLabel scandinaviaLabel;
    private javax.swing.JLabel siamLabel;
    private javax.swing.JLabel siberiaLabel;
    private javax.swing.JLabel statiUnitiOccLabel;
    private javax.swing.JLabel statiUnitiOriLabel;
    private javax.swing.JLabel territorioNOLabel;
    private javax.swing.JLabel ucrainaLabel;
    private javax.swing.JLabel uraliLabel;
    private javax.swing.JLabel venezuelaLabel;
    // End of variables declaration//GEN-END:variables


}
