/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrameCountdown.java
 *
 * Created on 25-mag-2011, 12.53.55
 */

package virtualrisikoii.risiko;

import java.awt.Color;
import java.awt.Frame;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.Toolkit;
import java.text.Normalizer.Form;
import javax.swing.JFrame;

/**
 *
 * @author Administrator
 */
public class JFrameCountdown extends javax.swing.JFrame implements Runnable {

    /** Creates new form JFrameCountdown */
    public JFrameCountdown() {
        this.setBounds(65, 395, 100, 100);
        initComponents();
        setVisible(true);
        TuoThread tt = new TuoThread( this, 12000);
        tt.start();
        
        

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numeri = new virtualrisikoii.risiko.JPanelDadi();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setEnabled(false);
        setResizable(false);
        setUndecorated(true);

        numeri.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        numeri.setName("numeri");
        numeri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numeriMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                numeriMousePressed(evt);
            }
        });

        javax.swing.GroupLayout numeriLayout = new javax.swing.GroupLayout(numeri);
        numeri.setLayout(numeriLayout);
        numeriLayout.setHorizontalGroup(
            numeriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        numeriLayout.setVerticalGroup(
            numeriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(numeri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(numeri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numeriMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numeriMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeriMousePressed

    private void numeriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numeriMouseClicked
        // TODO add your handling code here:
   
    }//GEN-LAST:event_numeriMouseClicked

    /**
    * @param args the command line arguments
    */

    public void run() {
   int i=0;
   Image img;
   int time=1500;
   String nomeCartaProb = null;

   Suono.playSound("/virtualrisikoii/resources/dadi/time.wav");

   try { Thread.sleep(2000);}
       catch (InterruptedException e) {
       e.printStackTrace();}

    while(i<10){

        Suono.playSound("/virtualrisikoii/resources/dadi/beepTimer.wav");
        img=Toolkit.getDefaultToolkit().createImage("src/virtualrisikoii/resources/countdown/"+i+".png");
        numeri.setImage(img);
        numeri.repaint();

            try { Thread.sleep(1000);}
       catch (InterruptedException e) {
       e.printStackTrace();}
        i++;

   }



   }



    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               JFrameCountdown frame= new JFrameCountdown();
                  
                  //  frame.setVisible(true);
                     Thread t=new Thread(frame);
                     t.start() ;

           }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private virtualrisikoii.risiko.JPanelDadi numeri;
    // End of variables declaration//GEN-END:variables

}



