/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrameScambioCarte.java
 *
 * Created on 10-giu-2011, 10.38.07
 */

package virtualrisikoii.risiko;

import java.awt.GraphicsEnvironment;
import javax.swing.JFrame;

/**
 *
 * @author Administrator
 */
public class JFrameScambioCarte extends javax.swing.JFrame {

    /** Creates new form JFrameScambioCarte */
    public JFrameScambioCarte(Giocatore giocatore, Carta carta1, Carta carta2, Carta carta3, int rinforzi) {
        setCenterScreen(this);
        initComponents();
         String player = giocatore.getNome();
         String card1= carta1.getNome();
         String card2= carta2.getNome();
         String card3= carta3.getNome();
         String terr1=carta1.getTerritorio().getNome();
         String terr2=carta2.getTerritorio().getNome();
         String terr3=carta3.getTerritorio().getNome();
         String path1="/virtualrisikoii/resources/cards/"+card1+".jpg";
         String path2="/virtualrisikoii/resources/cards/"+card2+".jpg";
         String path3="/virtualrisikoii/resources/cards/"+card3+".jpg";
         giocatoreLabel.setText(player);
         carta1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource(path1)));
         carta2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource(path2)));
         carta3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource(path3)));
         nomecarta1Label.setText(terr1);
         nomecarta2Label.setText(terr2);
         nomecarta3Label.setText(terr3);
         numeroRinforziLabel.setText(Integer.toString(rinforzi));
         TuoThread tt = new TuoThread( this, 7000 );
         tt.start();



    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        giocatoreLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        carta1Label = new javax.swing.JLabel();
        carta2Label = new javax.swing.JLabel();
        carta3Label = new javax.swing.JLabel();
        nomecarta1Label = new javax.swing.JLabel();
        nomecarta2Label = new javax.swing.JLabel();
        nomecarta3Label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numeroRinforziLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Il ");
        jLabel1.setName("jLabel1"); // NOI18N

        giocatoreLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        giocatoreLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        giocatoreLabel.setText("giocatore  giallo");
        giocatoreLabel.setName("giocatoreLabel"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("ha giocato le seguenti carte:");
        jLabel2.setName("jLabel2"); // NOI18N

        carta1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualrisikoii/resources/cards/cannone.jpg"))); // NOI18N
        carta1Label.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        carta1Label.setName("carta1Label"); // NOI18N

        carta2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualrisikoii/resources/cards/cannone.jpg"))); // NOI18N
        carta2Label.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        carta2Label.setName("carta2Label"); // NOI18N

        carta3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualrisikoii/resources/cards/cannone.jpg"))); // NOI18N
        carta3Label.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        carta3Label.setName("carta3Label"); // NOI18N

        nomecarta1Label.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        nomecarta1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomecarta1Label.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nomecarta1Label.setName("nomecarta1Label"); // NOI18N

        nomecarta2Label.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        nomecarta2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomecarta2Label.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nomecarta2Label.setName("nomecarta2Label"); // NOI18N

        nomecarta3Label.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        nomecarta3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomecarta3Label.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nomecarta3Label.setName("nomecarta3Label"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("rinforzi ottenuti");
        jLabel3.setName("jLabel3"); // NOI18N

        numeroRinforziLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        numeroRinforziLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        numeroRinforziLabel.setText("0");
        numeroRinforziLabel.setName("numeroRinforziLabel"); // NOI18N

        jButton1.setText("OK");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(giocatoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nomecarta1Label, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(carta1Label))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nomecarta2Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(carta2Label))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(carta3Label)
                            .addComponent(nomecarta3Label, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))))
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(numeroRinforziLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addContainerGap(241, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(giocatoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(carta1Label)
                    .addComponent(carta2Label)
                    .addComponent(carta3Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(nomecarta2Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(nomecarta3Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(nomecarta1Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(numeroRinforziLabel))
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new JFrameScambioCarte().setVisible(true);
            }
        });
    }
     public static void setCenterScreen(JFrame frame) {
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        java.awt.Point center = ge.getCenterPoint();
        java.awt.Rectangle bounds = ge.getMaximumWindowBounds();
        int w = Math.max(bounds.width/2, Math.min(frame.getWidth(), bounds.width));
        int h = Math.max(bounds.height/2, Math.min(frame.getHeight(), bounds.height));
        int x = center.x - w/2, y = center.y - h/2;
        frame.setBounds(x, y, w, h);
        if (w == bounds.width && h == bounds.height)
            frame.setExtendedState(frame.MAXIMIZED_BOTH);
        frame.validate();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel carta1Label;
    private javax.swing.JLabel carta2Label;
    private javax.swing.JLabel carta3Label;
    private javax.swing.JLabel giocatoreLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel nomecarta1Label;
    private javax.swing.JLabel nomecarta2Label;
    private javax.swing.JLabel nomecarta3Label;
    private javax.swing.JLabel numeroRinforziLabel;
    // End of variables declaration//GEN-END:variables

}
