/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UserStatisticFrame.java
 *
 * Created on 17-giu-2011, 13.09.22
 */

package corba.client;

import corba.SummaryPlayerInfo;
import javax.swing.table.TableModel;

/**
 *
 * @author root
 */
public class UserStatisticFrame extends javax.swing.JFrame {

    private SummaryPlayerInfo info;

    /** Creates new form UserStatisticFrame */
    public UserStatisticFrame(SummaryPlayerInfo info) {
        this.info=info;
        initComponents();
        setTitle("Risultati per :: "+info.username);
        int size=info.info.length;
        TableModel model=this.jTable1.getModel();
        for(int i=0;i<size;i++){
            model.setValueAt(info.info[i].gameName, i, 0);
            model.setValueAt(info.info[i].date, i, 1);
            model.setValueAt(info.info[i].score, i, 2);
            model.setValueAt(info.info[i].victory, i, 3);
        }
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new String [] {
                "partita", "data", "punteggio", "vincitore"
            },this.info.info.length
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setHeaderValue("partita");
        jTable1.getColumnModel().getColumn(1).setHeaderValue("data");
        jTable1.getColumnModel().getColumn(2).setHeaderValue("punteggio");
        jTable1.getColumnModel().getColumn(3).setHeaderValue("vincitore");

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public SummaryPlayerInfo getInfo() {
        return info;
    }

    public void setInfo(SummaryPlayerInfo info) {
        this.info = info;
    }

    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserStatisticFrame(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
