package org.domain.risikoweb.entity;

// Generated 6-lug-2011 21.18.40 by Hibernate Tools 3.4.0.CR1



/**
 * GameregistrationId generated by hbm2java
 */

public class GameregistrationId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2562311815633655673L;
	private String userUsername;
	private int gameId;

	public GameregistrationId() {
	}

	public GameregistrationId(String userUsername, int gameId) {
		this.userUsername = userUsername;
		this.gameId = gameId;
	}

	public String getUserUsername() {
		return this.userUsername;
	}

	public void setUserUsername(String userUsername) {
		this.userUsername = userUsername;
	}

	public int getGameId() {
		return this.gameId;
	}

	public void setGameId(int gameId) {
		this.gameId = gameId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GameregistrationId))
			return false;
		GameregistrationId castOther = (GameregistrationId) other;

		return ((this.getUserUsername() == castOther.getUserUsername()) || (this
				.getUserUsername() != null
				&& castOther.getUserUsername() != null && this
				.getUserUsername().equals(castOther.getUserUsername())))
				&& (this.getGameId() == castOther.getGameId());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getUserUsername() == null ? 0 : this.getUserUsername()
						.hashCode());
		result = 37 * result + this.getGameId();
		return result;
	}

}
