package corba;


/**
* corba/Authentication.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Corba.idl
* mercoledì 6 luglio 2011 18.07.58 CEST
*/

public final class Authentication implements org.omg.CORBA.portable.IDLEntity
{
  public String message = null;
  public corba.UserInfo info = null;

  public Authentication ()
  {
  } // ctor

  public Authentication (String _message, corba.UserInfo _info)
  {
    message = _message;
    info = _info;
  } // ctor

} // class Authentication
