package corba;


/**
* corba/RegistrationsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Corba.idl
* venerdì 1 luglio 2011 14.23.09 CEST
*/

public final class RegistrationsHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.RegistrationInfo value[] = null;

  public RegistrationsHolder ()
  {
  }

  public RegistrationsHolder (corba.RegistrationInfo[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.RegistrationsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.RegistrationsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.RegistrationsHelper.type ();
  }

}
