package corba;


/**
* corba/ResultInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Corba.idl
* venerdì 1 luglio 2011 14.23.09 CEST
*/

public final class ResultInfo implements org.omg.CORBA.portable.IDLEntity
{
  public String gameName = null;
  public String date = null;
  public int score = (int)0;
  public boolean victory = false;

  public ResultInfo ()
  {
  } // ctor

  public ResultInfo (String _gameName, String _date, int _score, boolean _victory)
  {
    gameName = _gameName;
    date = _date;
    score = _score;
    victory = _victory;
  } // ctor

} // class ResultInfo
