package corba;


/**
* corba/RisikoServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Corba.idl
* martedì 7 giugno 2011 20.10.13 CEST
*/

public interface RisikoServer extends RisikoServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RisikoServer
