package corba;


/**
* corba/RisikoServerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Corba.idl
* martedì 7 giugno 2011 20.10.13 CEST
*/

public abstract class RisikoServerPOA extends org.omg.PortableServer.Servant
 implements corba.RisikoServerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("authenticate", new java.lang.Integer (0));
    _methods.put ("getAvailableGames", new java.lang.Integer (1));
    _methods.put ("getCurrentGame", new java.lang.Integer (2));
    _methods.put ("saveResult", new java.lang.Integer (3));
    _methods.put ("createGame", new java.lang.Integer (4));
    _methods.put ("signPlayer", new java.lang.Integer (5));
    _methods.put ("getAuthenticateUsers", new java.lang.Integer (6));
    _methods.put ("getPlayers", new java.lang.Integer (7));
    _methods.put ("shutdown", new java.lang.Integer (8));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // corba/RisikoServer/authenticate
       {
         String usrname = in.read_string ();
         String pwd = in.read_string ();
         corba.UserInfo $result = null;
         $result = this.authenticate (usrname, pwd);
         out = $rh.createReply();
         corba.UserInfoHelper.write (out, $result);
         break;
       }

       case 1:  // corba/RisikoServer/getAvailableGames
       {
         corba.PartitaInfo $result[] = null;
         $result = this.getAvailableGames ();
         out = $rh.createReply();
         corba.GamesHelper.write (out, $result);
         break;
       }

       case 2:  // corba/RisikoServer/getCurrentGame
       {
         corba.UserInfo player = corba.UserInfoHelper.read (in);
         corba.PartitaInfo $result = null;
         $result = this.getCurrentGame (player);
         out = $rh.createReply();
         corba.PartitaInfoHelper.write (out, $result);
         break;
       }

       case 3:  // corba/RisikoServer/saveResult
       {
         corba.RegistrationInfo results[] = corba.ResultsHelper.read (in);
         boolean $result = false;
         $result = this.saveResult (results);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // corba/RisikoServer/createGame
       {
         corba.UserInfo u = corba.UserInfoHelper.read (in);
         short maxTurns = in.read_ushort ();
         short maxPlayers = in.read_ushort ();
         String name = in.read_string ();
         corba.PartitaInfo $result = null;
         $result = this.createGame (u, maxTurns, maxPlayers, name);
         out = $rh.createReply();
         corba.PartitaInfoHelper.write (out, $result);
         break;
       }

       case 5:  // corba/RisikoServer/signPlayer
       {
         corba.UserInfo player = corba.UserInfoHelper.read (in);
         corba.PartitaInfo partita = corba.PartitaInfoHelper.read (in);
         boolean $result = false;
         $result = this.signPlayer (player, partita);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 6:  // corba/RisikoServer/getAuthenticateUsers
       {
         corba.UserInfo $result[] = null;
         $result = this.getAuthenticateUsers ();
         out = $rh.createReply();
         corba.PlayersHelper.write (out, $result);
         break;
       }

       case 7:  // corba/RisikoServer/getPlayers
       {
         corba.PartitaInfo partita = corba.PartitaInfoHelper.read (in);
         corba.UserInfo $result[] = null;
         $result = this.getPlayers (partita);
         out = $rh.createReply();
         corba.PlayersHelper.write (out, $result);
         break;
       }

       case 8:  // corba/RisikoServer/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:corba/RisikoServer:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public RisikoServer _this() 
  {
    return RisikoServerHelper.narrow(
    super._this_object());
  }

  public RisikoServer _this(org.omg.CORBA.ORB orb) 
  {
    return RisikoServerHelper.narrow(
    super._this_object(orb));
  }


} // class RisikoServerPOA
