package corba;


/**
* corba/StatisticsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Corba.idl
* martedì 12 luglio 2011 17.24.43 CEST
*/

public final class StatisticsHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.Summary value[] = null;

  public StatisticsHolder ()
  {
  }

  public StatisticsHolder (corba.Summary[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.StatisticsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.StatisticsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.StatisticsHelper.type ();
  }

}
