package corba;

/**
* corba/AuthenticationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Corba.idl
* mercoledì 6 luglio 2011 18.07.58 CEST
*/

public final class AuthenticationHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.Authentication value = null;

  public AuthenticationHolder ()
  {
  }

  public AuthenticationHolder (corba.Authentication initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.AuthenticationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.AuthenticationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.AuthenticationHelper.type ();
  }

}
