package corba;


/**
* corba/PlayerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Corba.idl
* mercoledì 6 luglio 2011 18.07.58 CEST
*/

public interface PlayerOperations 
{
  corba.UserInfo getUserInfo ();
  void notifyNewGame (corba.PartitaInfo partita);
  void notifyNewRegistration (corba.RegistrationInfo registration);
  void notifyStart (String managerName);
  void notifyNewPlayer (corba.UserInfo userInfo);
  boolean isLogged ();
} // interface PlayerOperations
