package corba;


/**
* corba/Player.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Corba.idl
* martedì 5 luglio 2011 16.28.52 CEST
*/

public interface Player extends PlayerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Player
