package corba;


/**
* corba/RisikoServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Corba.idl
* martedì 12 luglio 2011 17.24.43 CEST
*/

public interface RisikoServer extends RisikoServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RisikoServer
