package corba;


/**
* corba/RisikoServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Corba.idl
* mercoledì 6 luglio 2011 18.07.58 CEST
*/

public interface RisikoServer extends RisikoServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RisikoServer
