package corba;


/**
* corba/SummaryPlayerInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Corba.idl
* venerdì 17 giugno 2011 4.01.34 CEST
*/

public final class SummaryPlayerInfo implements org.omg.CORBA.portable.IDLEntity
{
  public String username = null;
  public corba.ResultInfo info[] = null;

  public SummaryPlayerInfo ()
  {
  } // ctor

  public SummaryPlayerInfo (String _username, corba.ResultInfo[] _info)
  {
    username = _username;
    info = _info;
  } // ctor

} // class SummaryPlayerInfo
