package corba;

/**
* corba/UserDetailsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Corba.idl
* martedì 12 luglio 2011 17.24.43 CEST
*/

public final class UserDetailsHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.UserDetails value = null;

  public UserDetailsHolder ()
  {
  }

  public UserDetailsHolder (corba.UserDetails initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.UserDetailsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.UserDetailsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.UserDetailsHelper.type ();
  }

}
