/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * dadiGui.java
 *
 * Created on 20-mag-2011, 0.53.34
 */

package virtualrisikoii;

/**
 *
 * @author Administrator
 */
public class dadiGui extends javax.swing.JFrame {
    private final int att1;
    private final int att2;
    private final int att3;
    private final int dif1;
    private final int dif2;
    private final int dif3;
    private final int giocAtt;
    private final int giocDif;
    private String descrizione=null;

    /** Creates new form dadiGui */
    public dadiGui(String descriz,int att1,int att2,int att3,int dif1,int dif2,int dif3,int giocAtt,int giocDif) {
        setTitle("Lancio dadi ...");
        this.descrizione=descriz;
        this.att1=att1;
        this.att2=att2;
        this.att3=att3;
        this.dif1=dif1;
        this.dif2=dif2;
        this.dif3=dif3;
        this.giocAtt=giocAtt;
        this.giocDif=giocDif;
        initComponents();
        TuoThread tt = new TuoThread( this, 15000 );
        tt.start();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Ok");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dadiGui("attacco da frigento a gesualdo",1,1,1,1,2,3,1,4).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

}
