/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrameTurno.java
 *
 * Created on 23-mag-2011, 21.10.07
 */

package virtualrisikoii;

import java.awt.Color;
import java.awt.GraphicsEnvironment;
import javax.swing.JFrame;
import virtualrisikoii.risiko.Suono;

/**
 *
 * @author Administrator
 */
public class JFrameTurno extends javax.swing.JFrame {

    /** Creates new form JFrameTurno */
    public JFrameTurno(int giocatore) {
        String pathColore=null;
        String colore=null;
        Color color;
        setCenterScreen(this);
        initComponents();
        switch(giocatore){
            case 0: colTurno="red" ;
                    colore="Rosso";

            break;
            case 1: colTurno="yellow";
                    colore="Giallo";
            break;
            case 2: colTurno="green";
                    colore="Verde";
            break;
            case 3: colTurno="black";
                    colore="Nero";
            break;
            case 4: colTurno="purple";
                    colore="Viola";
            break;
            case 5: colTurno="blue";
                    colore="Blu";
            break;
        }


        pathColore="/virtualrisikoii/resources/carro/"+colTurno+".png";
        coloreTurno.setText(colore);

        switch(giocatore){
            case 0:  coloreTurno.setForeground(Color.RED);

            break;
            case 1:  coloreTurno.setForeground(Color.YELLOW);
            break;
            case 2:  coloreTurno.setForeground(Color.GREEN);
            break;
            case 3:  coloreTurno.setForeground(Color.BLACK);
            break;
            case 4:  coloreTurno.setForeground(Color.MAGENTA);
            break;
            case 5:  coloreTurno.setForeground(Color.BLUE);
            break;
        }

        iconaTurno.setIcon(new javax.swing.ImageIcon(getClass().getResource(pathColore)));
     
        
        Suono.playSound("/virtualrisikoii/resources/dadi/DingLing.wav");
       TuoThread tt = new TuoThread( this, 5000 );
       tt.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        coloreTurno = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        iconaTurno = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        coloreTurno.setFont(new java.awt.Font("Times New Roman", 1, 18));
        coloreTurno.setName("coloreTurno"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel2.setText("E' il TURNO del giocatore :");
        jLabel2.setName("jLabel2"); // NOI18N

        iconaTurno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualrisikoii/resources/carro/green.png"))); // NOI18N
        iconaTurno.setName("iconaTurno"); // NOI18N

        jButton1.setText("OK");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(coloreTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(iconaTurno)))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coloreTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(36, 36, 36)
                .addComponent(iconaTurno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameTurno(4).setVisible(true);
            }
        });
    }
        public static void setCenterScreen(JFrame frame) {
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        java.awt.Point center = ge.getCenterPoint();
        java.awt.Rectangle bounds = ge.getMaximumWindowBounds();
        int w = Math.max(bounds.width/2, Math.min(frame.getWidth(), bounds.width));
        int h = Math.max(bounds.height/2, Math.min(frame.getHeight(), bounds.height));
        int x = center.x - w/2, y = center.y - h/2;
        frame.setBounds(x, y, w, h);
        if (w == bounds.width && h == bounds.height)
            frame.setExtendedState(frame.MAXIMIZED_BOTH);
        frame.validate();


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel coloreTurno;
    private javax.swing.JLabel iconaTurno;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
    private String colTurno;
}
